### ISSUE TITLE
Issue with gmes_petap.pl while running BRAKER on RNA-Seq

### ISSUE THREAD

**Issue by tayabsoomro** [Gaius-Augustus/BRAKER#175] opened 2020-02-27 19:13 UTC
**ISSUE**
I am trying to run BRAKER pipeline on my assembled genome and raw unassembled RNA-Seq data pertaining to that organism. I run into an issue which according to BRAKER is due to not having sufficient multiplicity information. I would like to know what the "multiplicity" means and how to interpret the following statement:

> The hints file(s) for GeneMark-EX contain less than **150 introns** with **multiplicity >= 10!** (In total, **1779 unique introns** are contained. **26 have a multiplicity >= 10**.)

Here is the reference to the if-statement that the program lands on: The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 10! (In total, 1779 unique introns are contained. 26 have a multiplicity >= 10.)

___

**DETAILS OF THE RUN**

I am running the program as follows:

```
$ braker.pl --species=yourSpecies --genome=p27run7_neg_contigs-34,5,33,25,36,21.fasta --bam=RNASeqAlignedTop27run7.sorted.bam
```

The BAM file that is provided to BRAKER was generated using `bwa mem` command as follows:

```
bwa mem genome.fasta all_raw_rna.fasta -t 20 > RNASeqAlignedTop27run7.sam
```

The output that I get from the above braker command is shown below:

```
soomrot@sksaska415801d run1 % braker.pl --species=yourSpecies --genome=p27run7_neg_contigs-34,5,33,25,36,21.fasta --bam=RNASeqAlignedTop27run7.sorted.bam
# Thu Feb 27 11:59:47 2020: Log information is stored in file /Users/soomrot/Documents/BrakerRun1/run1/braker/braker.log
#*********
# WARNING:
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 10! (In total, 1779 unique introns are contained. 26 have a multiplicity >= 10.) Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set (orthodb_small.fa).
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
#*********
ERROR in file /Users/soomrot/Documents/software/BRAKER-2.1.5/scripts/braker.pl at line 6372
Failed to execute: perl /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap/gmes_petap.pl --verbose --sequence=/Users/soomrot/Documents/BrakerRun1/run1/braker/genome.fa --ET=/Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=1 --gc_donor 0.001 1>/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap/gmes_petap.pl --verbose --sequence=/Users/soomrot/Documents/BrakerRun1/run1/braker/genome.fa --ET=/Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=1 --gc_donor 0.001 1>/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!
```

And inside the error folder in braker (`run1/braker/errors/GenMark-ET.stderr`), here is the output for GeneMark-ET:
```
Unknown option: gc_donor
```

And finally, I tracked down the error in the code, and here is the link to the if-statement that the program lands on: https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/braker.pl#L6239-L6259

Any help?

Regards,
Tayab

**Comment by KatharinaHoff** [comment] 2020-02-27 19:46
If the alignment of a single read supports a putative intron, the
multiplicity for that intron is 1. If two reads support the same intron,
the multiplicity is 2, and so on.

Typically, Illumina RNAseq allows to obtain sufficient multiplicity for
BRAKER. If you did not use all available libraries on SRA already, try
VARUS.

**Comment by KatharinaHoff** [comment] 2020-02-27 19:48
You must use an aligner that produces spliced alignments! For example Hisat2.

**Comment by tayabsoomro** [comment] 2020-03-10 20:23
Hi Kathrina,

So I did what you suggested. I aligned my RNA-Seq data using HISAT2. But now I am running into the following issue:

```
soomrot@sksaska415801d run1 % ~/Documents/software/BRAKER-2.1.5/scripts/braker.pl --species=yourSpecies --genome=p27run7_neg_contigs-34,5,33,25,36,21.fasta --bam=RNASeqAlignedTop27run7_using_hisat2.sorted.bam
# Tue Mar 10 12:55:41 2020: Log information is stored in file /Users/soomrot/Documents/BrakerRun1/run1/braker/braker.log
ERROR in file /Users/soomrot/Documents/software/BRAKER-2.1.5/scripts/braker.pl at line 6372
Failed to execute: perl /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap/gmes_petap.pl --verbose --sequence=/Users/soomrot/Documents/BrakerRun1/run1/braker/genome.fa --ET=/Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=1 --gc_donor 0.001 1>/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap/gmes_petap.pl --verbose --sequence=/Users/soomrot/Documents/BrakerRun1/run1/braker/genome.fa --ET=/Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff --et_score 10 --max_intergenic 50000 --cores=1 --gc_donor 0.001 1>/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!
```

Here is the full `braker.log`:

```
#**********************************************************************************
#                               BRAKER CONFIGURATION
#**********************************************************************************
# BRAKER CALL: /Users/soomrot/Documents/software/BRAKER-2.1.5/scripts/braker.pl --species=yourSpecies --genome=p27run7_neg_contigs-34,5,33,25,36,21.fasta --bam=RNASeqAlignedTop27run7_using_hisat2.sorted.bam
# Tue Mar 10 13:38:47 2020: braker.pl version 2.1.5
# Tue Mar 10 13:38:47 2020: Configuring of BRAKER for using external tools...
# Tue Mar 10 13:38:47 2020: Found environment variable $AUGUSTUS_CONFIG_PATH. Setting $AUGUSTUS_CONFIG_PATH to /Users/soomrot/Documents/software/Augustus/config
# Tue Mar 10 13:38:47 2020: Found environment variable $AUGUSTUS_BIN_PATH. Setting $AUGUSTUS_BIN_PATH to /Users/soomrot/Documents/software/Augustus/bin
# Tue Mar 10 13:38:47 2020: Found environment variable $AUGUSTUS_SCRIPTS_PATH. Setting $AUGUSTUS_SCRIPTS_PATH to /Users/soomrot/Documents/software/Augustus/scripts
# Tue Mar 10 13:38:47 2020: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap
# Tue Mar 10 13:38:47 2020: Did not find environment variable $BAMTOOLS_PATH (either variable does not exist, or the path given in variable does not exist). Will try to set this variable in a different way, later.
# Tue Mar 10 13:38:47 2020: Trying to guess $BAMTOOLS_BIN_PATH from location of bamtools executable that is available in your $PATH
# Tue Mar 10 13:38:47 2020: Setting $BAMTOOLS_BIN_PATH to /usr/local/bin
# Tue Mar 10 13:38:47 2020: Did not find environment variable $SAMTOOLS_PATH  (either variable does not exist, or the path given in variable doesnot exist). Will try to set this variable in a different way, later.
# Tue Mar 10 13:38:47 2020: Trying to guess $SAMTOOLS_PATH from location of samtools executable in your $PATH
# Tue Mar 10 13:38:47 2020: Setting $SAMTOOLS_PATH to /usr/local/bin
# Tue Mar 10 13:38:47 2020: Did not find environment variable $DIAMOND_PATH
# Tue Mar 10 13:38:47 2020: Trying to guess $DIAMOND_PATH from location of diamond executable that is available in your $PATH
#*********
# WARNING: Guessing the location of $DIAMOND_PATH failed / BRAKER failed  to detect a diamond binary with "which diamond"!
#*********
# Tue Mar 10 13:38:47 2020: Found environment variable $BLAST_PATH. Setting $BLAST_PATH to /Users/soomrot/Documents/software/ncbi-blast-2.10.0+/bin
# Tue Mar 10 13:38:47 2020: Did not find environment variable $PYTHON3_PATH
# Tue Mar 10 13:38:47 2020: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Tue Mar 10 13:38:47 2020: Setting $PYTHON3_PATH to /usr/local/bin
# Tue Mar 10 13:38:47 2020: Found environment variable $CDBTOOLS_PATH. Setting $CDBTOOLS_PATH to /Users/soomrot/Documents/software/cdbfasta
#**********************************************************************************
#                               CREATING DIRECTORY STRUCTURE
#**********************************************************************************
# Tue Mar 10 13:38:47 2020: creating file that contains citations for this BRAKER run at /Users/soomrot/Documents/BrakerRun1/run1/braker/what-to-cite.txt...
# Tue Mar 10 13:38:48 2020: changing into working directory /Users/soomrot/Documents/BrakerRun1/run1/braker
cd /Users/soomrot/Documents/BrakerRun1/run1/braker
# Tue Mar 10 13:38:48 2020: Creating parameter template files for AUGUSTUS with new_species.pl
# Tue Mar 10 13:38:48 2020: new_species.pl will create parameter files for species yourSpecies in /Users/soomrot/Documents/software/Augustus/config/species/yourSpecies
perl /Users/soomrot/Documents/software/Augustus/scripts/new_species.pl --species=yourSpecies --AUGUSTUS_CONFIG_PATH=/Users/soomrot/Documents/software/Augustus/config 1> /dev/null 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/new_species.stderr
# Tue Mar 10 13:38:48 2020: check_fasta_headers(): Checking fasta headers of file /Users/soomrot/Documents/BrakerRun1/run1/p27run7_neg_contigs-34,5,33,25,36,21.fasta
#*********
 WARNING: empty line was removed! This warning will be supressed from now on!
#*********
#**********************************************************************************
#                               PROCESSING HINTS
#**********************************************************************************
# Tue Mar 10 13:38:48 2020: Converting bam files to hints
# Tue Mar 10 13:38:48 2020: Checking bam headers
# Tue Mar 10 13:38:48 2020: create header file /Users/soomrot/Documents/BrakerRun1/run1/braker/RNASeqAlignedTop27run7_using_hisat2_header.sam
/usr/local/bin/bamtools header -in /Users/soomrot/Documents/BrakerRun1/run1/RNASeqAlignedTop27run7_using_hisat2.sorted.bam > /Users/soomrot/Documents/BrakerRun1/run1/braker/RNASeqAlignedTop27run7_using_hisat2_header.sam
# Tue Mar 10 13:38:48 2020: Deleting SAM header file /Users/soomrot/Documents/BrakerRun1/run1/braker/RNASeqAlignedTop27run7_using_hisat2_header.sam (will not be needed from here on)
# Tue Mar 10 13:38:48 2020: Deleting /Users/soomrot/Documents/BrakerRun1/run1/braker/RNASeqAlignedTop27run7_using_hisat2_new_header.sam
# Tue Mar 10 13:38:48 2020: make hints from BAM file /Users/soomrot/Documents/BrakerRun1/run1/RNASeqAlignedTop27run7_using_hisat2.sorted.bam
/Users/soomrot/Documents/software/Augustus/bin/bam2hints --intronsonly --in=/Users/soomrot/Documents/BrakerRun1/run1/RNASeqAlignedTop27run7_using_hisat2.sorted.bam --out=/Users/soomrot/Documents/BrakerRun1/run1/braker/bam2hints.temp.0.gff 1> /Users/soomrot/Documents/BrakerRun1/run1/braker/errors/bam2hints.0.stdout 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/bam2hints.0.stderr
# Tue Mar 10 14:15:49 2020: add hints from BAM file /Users/soomrot/Documents/BrakerRun1/run1/RNASeqAlignedTop27run7_using_hisat2.sorted.bam to hints file
cat /Users/soomrot/Documents/BrakerRun1/run1/braker/bam2hints.temp.0.gff >>/Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.temp.gff
# Tue Mar 10 14:15:49 2020: Checking for hints of src=C and with grp tags that should not be joined according to multiplicity
# Tue Mar 10 14:15:49 2020: Joining hints that are identical (& from the same source) into multiplicity hints (input file /Users/soomrot/Documents/BrakerRun1/run1/braker/tmp_merge_hints.gff)
# Tue Mar 10 14:15:49 2020: sort hints of type rnaseq
cat /Users/soomrot/Documents/BrakerRun1/run1/braker/tmp_merge_hints.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/Users/soomrot/Documents/BrakerRun1/run1/braker/hints.rnaseq.temp.sort.gff
# Tue Mar 10 14:15:49 2020: join multiple hints
perl /Users/soomrot/Documents/software/Augustus/scripts/join_mult_hints.pl </Users/soomrot/Documents/BrakerRun1/run1/braker/hints.rnaseq.temp.sort.gff >/Users/soomrot/Documents/BrakerRun1/run1/braker/tmp_merge_hints.gff 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/join_mult_hints.rnaseq.stderr
mv /Users/soomrot/Documents/BrakerRun1/run1/braker/tmp_merge_hints.gff /Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.temp.gff
# Tue Mar 10 14:15:49 2020: filter introns, find strand and change score to 'mult' entry
perl /Users/soomrot/Documents/software/BRAKER-2.1.5/scripts/filterIntronsFindStrand.pl /Users/soomrot/Documents/BrakerRun1/run1/braker/genome.fa /Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.temp.gff --score 1>>/Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.gff 2>/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/filterIntronsFindStrand.stderr
# Tue Mar 10 14:15:50 2020: rm /Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.temp.gff
# Tue Mar 10 14:15:50 2020: Preparing hints for running GeneMark
# Tue Mar 10 14:15:50 2020: Filtering intron hints for GeneMark from /Users/soomrot/Documents/BrakerRun1/run1/braker/hintsfile.gff...
cat /Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff.rnaseq | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /Users/soomrot/Documents/software/Augustus/scripts/join_mult_hints.pl > /Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff.rnaseq.tmp
mv /Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff.rnaseq.tmp /Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff
#**********************************************************************************
#                              RUNNING GENEMARK-EX
#**********************************************************************************
# Tue Mar 10 14:15:51 2020: Checking whether file /Users/soomrot/Documents/BrakerRun1/run1/braker/genemark_hintsfile.gff contains sufficient multiplicity information...
# Tue Mar 10 14:15:52 2020: Executing GeneMark-ET
```

I updated the `~/.gm_key` file but I still cannot get it to work. Any ideas as to what is happening?

**Comment by KatharinaHoff** [comment] 2020-03-11 10:03
@tomasbruna maybe you know why GeneMark-ET dies?

**Comment by tomasbruna** [comment] 2020-03-12 23:13
Hi, is there anything in the `/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout` or `/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr` files?

The latest distribution of the GeneMark suite now comes with a script which you can use to verify that everything related to GeneMark-ET was installed correctly:

    cd  path_to_GeneMark-ET/
    ./check_install.bash

@KatharinaHoff I will update BRAKER's readme with this info (and some other improvements to the GeneMark suite) soon.

**Comment by cai1991** [comment] 2020-03-13 10:11
@tomasbruna Hello, Tomasbruna, I am also running BRAKER2 and encountered some problems caused by GeneMarker-ET.
The output for `./check_install.bash` is as follows:
`Checking GeneMark-ES installation`
`Error, installation key is missing or expired`
I have copied a fresh key to my home directory with right name.

output for `./gmhmme3 -v` is `Segmentation fault`.

Do you have any idea about the problem? Thanks a lot.

Kind regards,
Chengcheng

**Comment by tomasbruna** [comment] 2020-03-15 23:17
Hi Chengcheng,

this is probably an OS related issue -- are you running the program on a 64-bit Linux?

I am not a maintainer of the `gmhmme3` binary, please contact Alexandre Lomsadze (contact here http://exon.gatech.edu/GeneMark/contact.html) if the problem persists.

Best,
Tomas

**Comment by cai1991** [comment] 2020-03-16 03:32
@tomasbruna 
Hello Tomas,

Thanks for your reply. I run this program on the following system:
`Linux jacqueline-i 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`
Actually, I am awaiting a reply from Alexandre.

Best regards,
Chengcheng

**Comment by tayabsoomro** [comment] 2020-03-17 18:55
> Hi, is there anything in the `/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout` or `/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr` files?

@tomasbruna 
Here is what's in `/Users/soomrot/Documents/BrakerRun1/run1/braker/GeneMark-ET.stdout`:

```
error on command line: /Users/soomrot/Documents/software/gm_et_macosx/gmes_petap/gmes_petap.pl
```

And here's what's in `/Users/soomrot/Documents/BrakerRun1/run1/braker/errors/GeneMark-ET.stderr`

```
Unknown option: gc_donor
```

I think that I might have installed Linux version of GenMark-EX on my Mac. I cannot find Mac version of GeneMark-EX in the downloads page of GeneMark and I need that for BRAKER:

![image](https://user-images.githubusercontent.com/19979068/76891329-6afe2600-684e-11ea-93dd-5e4b37fe9b0e.png)

**Comment by pezhmansafdari** [comment] 2020-03-20 11:30
Hi,

I have the same problem. I noticed that there is no  --gc_donor option in gmes_petap.pl (or at least the two versions that I have). The error happens when BARKER tries to use an option that does not exist.

Any help would be appreciated.
BR, Pezhman

**Comment by tomasbruna** [comment] 2020-03-20 19:11
Hello,

I notified Alexandre Lomsadze about this issue, he is preparing the Mac OS version of the GeneMark-ES/ET/EP suite. I hope we can prepare the Mac OS version soon.

You are correct, the older Mac OS version is missing some features and won't work with the current BRAKER code. A temporary workaround could be to install an older BRAKER2 release -- https://github.com/Gaius-Augustus/BRAKER/releases, v2.1.4.

Tomas

**Comment by bioinfowheat** [comment] 2020-09-02 11:32
Hello, I am having exactly this problem, with a fresh install of GeneMark-ES/ET/EP on Linux64, but when I'm trying to use the provided gm_key_64.gz file ... this is not recognized by the software, e.g.

# getting new one
wget http://topaz.gatech.edu/GeneMark/tmp/GMtool_IH8XG/gm_key_64.gz
# move key from local to home
gunzip gm_key_64.gz
cp gm_key_64 ~/.gm_key
cd /mnt/griffin/chrwhe/software/braker_dependencies/gmes_linux_64/
./check_install.bash
Checking GeneMark-ES installation
Error, installation key is missing or expired

**Comment by Zachary-Wu** [comment] 2020-10-15 13:31
Hello, I am having this problem, when I  checking GeneMark-ES installation，" All required components for GeneMark-ES were found ",  but when I'm trying to use the braker.pl, there will have an error that "ERROR in file /miniconda3/envs/braker_env/bin/braker.pl at line 6372, the most common problem is an expired or not present file ~/.gm_key!“. 

Any help would be appreciated.

**Comment by tomasbruna** [comment] 2020-10-15 18:55
Hello,

can you share the full BRAKER log?

Also, are you encountering this error when using your own data or when using one of the example inputs?

Thanks,
Tomas

**Comment by Zachary-Wu** [comment] 2020-10-16 02:03
Hi, @tomasbruna

Thank you for the speedy reply.

Found the problem.
I recall that the conda env of BRAKER was deactivated when I install GeneMark-ES, and the Perl path of BRAKER_env is ".../miniconda3/envs/braker_env/bin/perl". So I run the "gmes_linux_64/change_path_in_perl_scripts.pl" and  make it right.

reference: [funannotate/issues/242](https://github.com/nextgenusfs/funannotate/issues/242)

**Comment by pierrj** [comment] 2020-12-04 01:03
I was having similar issues to those posted here where I was trying to use BRAKER v2.1.5 on Mac OS but it was not working for the reasons stated above: essentially the version of GeneMark-ES currently available for Mac OS is missing some options that v2.1.5 requires. I was able to combine the MacOS version of GeneMark-ES with the updated Linux version (instructions below) and can now use v2.1.5 with my chimeric version of GeneMark-ES just fine.

1) Download both Mac OS X and Linux 64 versions of GeneMark-ES
2) Compile Gibbs3 because the included version only works on 32bit Mac OS. To do this, untar and unzip gibbs-3.1.tar.gz in the GeneMark-ES for Mac OS directory. Then compile. Here is the command I used for this:
`sudo make CC='/usr/local/Cellar/gcc/10.2.0/bin/gcc-10' CFLAGS="-Wunused-but-set-variable"`
Finally replace old Gibbs3 with the new compiled one.
3) In the directory containing the Linux 64 versions of GeneMark-ES, replace the following executables with the ones of the same name in your Mac OS X version directory: Gibbs3, gmhmme3 and probuild.

Now you should be able to run gmes_petap.pl from the Linux 64 directory through BRAKER on your Mac just fine. Hope this helps other people out there that were stuck on this issue!

**Comment by KatharinaHoff** [comment] 2022-01-07 12:30
Thank you @pierrj , very useful instructions.

I will close this issue, now.

**Closed by KatharinaHoff** 2022-01-07 12:30 UTC
