### ISSUE TITLE
Can't locate File/HomeDir.pm in @INC

### ISSUE THREAD

**Issue by Lcornet** [Gaius-Augustus/BRAKER#19] opened 2019-01-31 18:28 UTC
Dear Braker team,

I have this problem when running BRAKER ;

./braker.pl 
Can't locate File/HomeDir.pm in @INC (you may need to install the File::HomeDir module) (@INC contains: /home/ulg/.local/share.cpan/build/GD-2.67-0/ /home/ulg/miniconda3/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi /home/ulg/miniconda3/lib/perl5/site_perl/5.22.0 /home/ulg/miniconda3/lib/perl5/5.22.0/x86_64-linux-thread-multi /home/ulg/miniconda3/lib/perl5/5.22.0 .) at ./braker.pl line 21.
BEGIN failed--compilation aborted at ./braker.pl line 21.

cpanm File::HomeDir
File::HomeDir is up to date. (1.004)

Can you help me ?

**Comment by KatharinaHoff** [comment] 2019-03-20 10:59
I assume that you are not using the Perl version that you think you are using? Check that carefully.

In any case, there are instructions for setting up an anaconda environment with all required Perl dependecies: https://github.com/Gaius-Augustus/BRAKER/issues/22

**Comment by KatharinaHoff** [comment] 2019-03-26 07:31
I will close this issue because a solution has been provided in the previous post.

**Closed by KatharinaHoff** 2019-03-26 07:31 UTC

**Comment by dangeles** [comment] 2020-02-24 03:10
Hi Katharina,

I installed BRAKER per instructions in the github, and got the exact same error as the user above. For installation of BRAKER, I created a new conda environment, and followed the instructions exactly as provided in the README. Issue #22 has additional instructions for the shebang in genemark perl scripts, but I don't understand why those instructions are there, since there are no instructions to clone the `genemark` repo in addition to BRAKER. 

I also tried downloading BRAKER2 from conda, but that gave an uninterpretable error:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:

(braker)
```

**Comment by KatharinaHoff** [comment] 2020-02-24 07:49
braker.pl runs a check for File::HomeDir that you can reproduce on your command line as follows (in bash for example):

```
perl -e 'uqw(check_install); $c = check_install(module => File::HomeDir); if($c){print "File::HomeDir is installed ok.\n"}else{print "File::HomeDir is not installed ok.\n"}'
```

Be sure to use the conda perl version (i.e. that you are in your conda environment).

GeneMark cannot be cloned. You need to download GeneMark from http://exon.gatech.edu/GeneMark/license_download.cgi and modify the scripts afterwards. 

The BRAKER conda receipe was created and is maintained by Natasha @npavlovikj . Maybe she can advise on how to solve the conda issue.

**Comment by npavlovikj** [comment] 2020-02-24 08:18
@dangeles , without more information about the exact conda command you used, I believe the error is because you are installing "braker" into already existing environment. I would suggest you to try creating new environment with "braker2" to avoid any version conflicts. `conda create -n braker2 braker2=2.1.5` followed with `conda activate braker2` worked fine for me.

**Comment by dangeles** [comment] 2020-02-24 16:41
@npavlovikj the commands I used were:
```
conda create -n braker
conda install -c bioconda braker2
```

My conda version is 4.8.2.

**Comment by npavlovikj** [comment] 2020-02-24 16:48
Thank @dangeles ! Do you do `conda activate braker` after `conda create` ? If not, then `conda install` is trying to install things in your base environment, which may cause the issue you observed.

Also, I am not sure of the order of your conda channels, you can also try `conda install -c conda-forge -c bioconda -c defaults braker2`. The packages in bioconda depend on the conda-forge and defaults channels, and if the order is not correct, you may get version issues as well.

**Comment by dangeles** [comment] 2020-02-24 16:59
`conda create` activates the new environment by default. Please assume I am installing `braker2` within the environment I created. 

`conda install -c conda-forge -c bioconda -c defaults braker2` works! That would be a helpful command to add to the conda page. Even so, the command gave the following warnings:

```
conda install -c conda-forge -c bioconda -c defaults braker2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done
```
Thanks @npavlovikj and @KatharinaHoff for the helpful responses!!! :D

**Comment by npavlovikj** [comment] 2020-02-24 17:02
I am glad that worked for you @dangeles , as long as the environment is created feel free to ignore the warnings :)
