### ISSUE TITLE
AUGUSTUS_CONFIG_PATH/species (in this case /.../Augustus/config/) is not writeable.

### ISSUE THREAD

**Issue by kataksk** [Gaius-Augustus/BRAKER#47] opened 2019-06-09 10:28 UTC
Hello!

I'm now trying to predict genes in novel genome with BRAKER. 
But I've got same errors.
I run the BRAKER with the following command:

/.../BRAKER/scripts/braker.pl --genome=/.../final.genome.scf.masked.sort.fasta --prot_seq=/.../compgene.fasta --prg=gth --ALIGNMENT_TOOL_PATH=/.../gth-1.7.1-Linux_x86_64-64bit/bin --trainFromGth --cores 30 --AUGUSTUS_CONFIG_PATH=/.../Augustus/config/

But I've got the following error:

Use of uninitialized value $species in concatenation (.) or string at /.../BRAKER/scripts/braker.pl line 1498.
Sun Jun  9 15:07:46 2019: braker.pl version 2.1.3

Sun Jun  9 15:07:46 2019: Configuring of BRAKER for using external tools...

Sun Jun  9 15:07:46 2019: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /.../Augustus/config.
Sun Jun  9 15:07:46 2019: ERROR: in file /.../BRAKER/scripts/braker.pl at line 1496
AUGUSTUS_CONFIG_PATH/species (in this case /.../Augustus/config/) is not writeable.
There are 3 alternative ways to set this variable for braker.pl:
   a) provide command-line argument --AUGUSTUS_CONFIG_PATH=/your/path
   b) use an existing environment variable $AUGUSTUS_CONFIG_PATH
      for setting the environment variable, run
           export AUGUSTUS_CONFIG_PATH=/your/path
      in your shell. You may append this to your .bashrc or
      .profile file in order to make the variable available to all
      your bash sessions.
   c) braker.pl can try guessing the location of
      $AUGUSTUS_CONFIG_PATH from an augustus executable that is
      available in your $PATH variable.
      If you try to rely on this option, you can check by typing
           which augustus
      in your shell, whether there is an augustus executable in
      your $PATH
      Be aware: the $AUGUSTUS_CONFIG_PATH must be writable for
                braker.pl because braker.pl is a pipeline that
                optimizes parameters that reside in that
                directory. This might be problematic in case you
                are using a system-wide installed augustus
                installation that resides in a directory that is
                not writable to you as a user.

So I checked whether the directory /.../Augustus/config/ is writable or not.
But it was obviously writable because I found the access permission like this:

[ ~ Augustus]$ ls -ltr
.....
drwxr-xr-x  7 ... qbg     72  ...  config

How could I fix this?
Any ideas would be appreciated!!
Thank you in advance!

**Comment by KatharinaHoff** [comment] 2019-08-16 14:24
It looks like your $AUGUSTUS_CONFIG_PATH is writable. Did you figure out what was your problem?

I fail to reproduce this problem on my machines. BRAKER currently responds correctly if I have a writable (works) or unwritable (fails) --AUGUSTUS_CONFIG_PATH parameter in the call.

Katharina

**Comment by KatharinaHoff** [comment] 2019-08-20 09:36
I am closing this issue because I don't see what needs to be fixed, at the moment, can't reproduce the problem. Please reopen if problems persists.

**Closed by KatharinaHoff** 2019-08-20 09:36 UTC
