### ISSUE TITLE
Segmentation fault w/ slurm

### ISSUE THREAD

**Issue by bro14002** [Gaius-Augustus/BRAKER#326] opened 2021-02-23 22:46 UTC
I’m trying to run BRAKER with a script on a server through slurm scheduler. When I do, the script fails and the error log shows this:

`# Thu Feb 11 16:59:38 2021: Configuring of BRAKER for using external tools...`
`# Thu Feb 11 16:59:38 2021: Configuring of BRAKER complete!`
`sh: line 1: 1423055 Segmentation fault      /home/FCAM/bosullivan/augustus/3.2.3/config/../bin/bam2hints --intronsonly --in=/home/FCAM/bosullivan/AmericanGenome/bam/sorted_JG-2800-18hr_L001.bam --out=/home/FCAM/bosullivan/braker/hirudo/bam2hints.temp.gff 2> /home/FCAM/bosullivan/braker/hirudo/errors/bam2hints.0.stderr`
`Failed to execute: /home/FCAM/bosullivan/augustus/3.2.3/config/../bin/bam2hints --intronsonly --in=/home/FCAM/bosullivan/AmericanGenome/bam/sorted_JG-2800-18hr_L001.bam --out=/home/FCAM/bosullivan/braker/hirudo/bam2hints.temp.gff 2>/home/FCAM/bosullivan/braker/hirudo/errors/bam2hints.0.stderr!`

Have you seen this error before? If so, any ideas on potential fixes?

**Comment by KatharinaHoff** [comment] 2021-02-24 09:44
Can you provide a toy data set that reproducibly leads to the segmentation
fault auf bam2hints?

Best,

Katharina

**Comment by KatharinaHoff** [comment] 2022-12-16 14:43
Closing because can't reproduce.

**Closed by KatharinaHoff** 2022-12-16 14:43 UTC
