### ISSUE TITLE
Regarding BRAKER2

### ISSUE THREAD

**Issue by aditi17142** [Gaius-Augustus/BRAKER#344] opened 2021-03-18 06:15 UTC
I have been trying to run braker. 

Command:
./braker.pl genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/augustus/config --AUGUSTUS_BIN_PATH=/home/Augustus/bin --AUGUSTUS_SCRIPTS_PATH=/home/Augustus/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
#**********************************************************************************
#                               BRAKER CONFIGURATION                               
#**********************************************************************************
# BRAKER CALL: ./braker.pl genome.fasta --hints=/home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/augustus/config --AUGUSTUS_BIN_PATH=/home/Augustus/bin --AUGUSTUS_SCRIPTS_PATH=/home/Augustus/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
# Thu Mar 18 11:37:17 2021: braker.pl version 2.1.5
# Thu Mar 18 11:37:17 2021: Checking whether hints from RNA-Seq and/or proteins are present in hintsfile
# Thu Mar 18 11:37:18 2021: REMARK: Protein input detected, BRAKER will be executed in the EP mode (--epmode).
# Thu Mar 18 11:37:18 2021: Configuring of BRAKER for using external tools...
# Thu Mar 18 11:37:18 2021: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /home/augustus/config.
# Thu Mar 18 11:37:18 2021: Setting $AUGUSTUS_BIN_PATH to command line argument --AUGUSTUS_BIN_PATH value /home/Augustus/bin.
# Thu Mar 18 11:37:18 2021: Setting $AUGUSTUS_SCRIPTS_PATH to command line argument --AUGUSTUS_SCRIPTS_PATH value /home/Augustus/scripts.
# Thu Mar 18 11:37:18 2021: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Thu Mar 18 11:37:18 2021: Setting $PYTHON3_PATH to /usr/bin
# Thu Mar 18 11:37:18 2021: Setting $GENEMARK_PATH to command line argument --GENEMARK_PATH value /home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES.
# Thu Mar 18 11:37:18 2021: Setting $DIAMOND_PATH to command line argument --DIAMOND_PATH value /home/Desktop/GenomeAnnotation/ProtHint/dependencies.
# Thu Mar 18 11:37:18 2021: Setting $CDBTOOLS_PATH to command line argument --CDBTOOLS_PATH value /home/Desktop/GenomeAnnotation/BRAKER/cdbfasta.
# Thu Mar 18 11:37:18 2021: Checking if input file /home/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff is in gff format
# Thu Mar 18 11:37:19 2021: BRAKER will execute GeneMark-EP for training GeneMark and generating a training gene set for AUGUSTUS, using protein information as sole extrinsic evidence source.
#*********
# IMPORTANT INFORMATION: no species for identifying the AUGUSTUS  parameter set that will arise from this BRAKER run was set. BRAKER will create an AUGUSTUS parameter set with name Sp_1. This parameter set can be used for future BRAKER/AUGUSTUS prediction runs for the same species. It is usually not necessary to retrain AUGUSTUS with novel extrinsic data if a high quality parameter set already exists.
#*********
# Thu Mar 18 11:37:19 2021: ERROR: in file ./braker.pl at line 4846
Genome file /home/Desktop/GenomeAnnotation/BRAKER/scripts does not exist.

While working with BRAKER, I have encountered this error.
ERROR: in file ./braker.pl at line 4846
Genome file /home/Desktop/GenomeAnnotation/BRAKER/scripts does not exist.

Kindly help in rectifying.

Thank you.

**Comment by tomasbruna** [comment] 2021-03-18 22:19
Hello,

please update your command line to `./braker.pl --genome=genome.fasta ...` instead of `./braker.pl genome.fasta ...`.

I've made the error message for this case more informative in b5bd08360299660f589d9ac3ed22deba8467cf0a

Best,
Tomas

**Comment by aditi17142** [comment] 2021-03-19 09:10
HI!
Its done. Thank you.

I have encountered this error and unable to rectify, kindly help.

 ./braker.pl --genome=genome.fasta --hints=/homel/Desktop/GenomeAnnotation/ProtHint/ProtOut/prothint_augustus.gff --softmasking --AUGUSTUS_CONFIG_PATH=/home/Desktop/config --AUGUSTUS_BIN_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/bin --AUGUSTUS_SCRIPTS_PATH=/home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts --GENEMARK_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies/GeneMarkES --DIAMOND_PATH=/home/Desktop/GenomeAnnotation/ProtHint/dependencies --CDBTOOLS_PATH=/home/Desktop/GenomeAnnotation/BRAKER/cdbfasta
# Fri Mar 19 14:34:09 2021: Log information is stored in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker/braker.log
ERROR: in file /home/Desktop/GenomeAnnotation/BRAKER/scripts/./helpMod.pm at line 307
 found neither /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/filterIntronsFindStrand.pl nor /home/Desktop/GenomeAnnotation/augustus-3.4.0/scripts/filterIntronsFindStrand.pl nor /home/Desktop/scripts/filterIntronsFindStrand.pl nor /home/Desktop/GenomeAnnotation/BRAKER/scripts/braker/filterIntronsFindStrand.pl!
Please check the environment variables AUGUSTUS_CONFIG_PATH and command-line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!

**Comment by tomasbruna** [comment] 2021-03-19 20:59
Closing because the issue is addressed in #119

**Closed by tomasbruna** 2021-03-19 20:59 UTC
