### ISSUE TITLE
Example test1.sh fails

### ISSUE THREAD

**Issue by mathog** [Gaius-Augustus/BRAKER#245] opened 2020-07-30 22:48 UTC
Reinstalled BRAKER today.  Existing Genemark-E* was 4.0.0, updated that to 4.59 (with a new key in .gm_key), then did:

```
  module load braker
  cd example
  wget http://bioinf.uni-greifswald.de/bioinf/braker/RNAseq.bam #for tests
  wget http://topaz.gatech.edu/GeneMark/Braker/RNAseq2.bam #for tests
  cd tests
  ./test1.sh
```

braker.log ends with:
```
#*********
# INFORMATION: the size of flanking region used in this BRAKER run is 1021. You might need this value if you later add a UTR training on top of an already existing BRAKER run.
#*********
# Thu Jul 30 15:33:52 2020: Genbank format file /home/common/src/braker/example/tests/test1/train.gb contains 267 genes.
#  Thu Jul 30 15:33:52 2020: concatenating good and downsampled GeneMark training genes to /home/common/src/braker/example/tests/test1/good_genes.lst.
cat /home/common/src/braker/example/tests/test1/GeneMark-ET/genemark.d.gtf > /home/common/src/braker/example/tests/test1/good_genes.lst
# Thu Jul 30 15:33:52 2020: Filtering train.gb for "good" mRNAs:
perl /home/common/modules/el8/x86_64/software/augustus/3.3.3-CentOS-vanilla/scripts/filterGenesIn_mRNAname.pl /home/common/src/braker/example/tests/test1/good_genes.lst /home/common/src/braker/example/tests/test1/train.gb > /home/common/src/braker/example/tests/test1/train.f.gb 2>/home/common/src/braker/example/tests/test1/errors/filterGenesIn_mRNAname.stderr
# Thu Jul 30 15:33:52 2020: Genbank format file /home/common/src/braker/example/tests/test1/train.f.gb contains 0 genes.
```
the files in the errors directory are all empty except for ensure_min_n_training_genes.stderr
 which contains:

`ensure_n_training_genes.py: warning: File with "bad" genes does not have enough genes to ensure 4000 genes. Adding all "bad" genes to the "good" gene set.
`

Any idea what may have gone wrong?

braker.log and the output from "cd test1; ls -alR" as test1_tree.log are attached.

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/5004103/braker.log)
[test1_tree.log](https://github.com/Gaius-Augustus/BRAKER/files/5004104/test1_tree.log)

**Comment by tomasbruna** [comment] 2020-07-31 00:42
Hello @mathog,

most likely, this is caused by an old version of `filterGenesIn_mRNAname.pl` script in AUGUSTUS.

You can either update the whole AUGUSTUS from its master branch (with `git clone git@github.com:Gaius-Augustus/Augustus.git`) or download just the `filterGenesIn_mRNAname.pl` script from https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/filterGenesIn_mRNAname.pl and replace the old version in the AUGUSTUS scripts folder.

I added this recommendation to the log file in https://github.com/Gaius-Augustus/BRAKER/commit/5ecde22f9615d8a9d0a7e2e177c9d1a9673c7a57.

Best,
Tomas

**Comment by mathog** [comment] 2020-07-31 16:26
OK.  The installation instructions prereq section here:

https://github.com/Gaius-Augustus/BRAKER#installation

lists "Augustus 3.3.3", which is the installed release.  There is a superscript F2 next to it (the link is actually to

https://github.com/Gaius-Augustus/BRAKER#g2

) which says:

`Please use the latest version of AUGUSTUS distributed by the original developers, it is available from github at https://github.com/Gaius-Augustus/Augustus. Problems have been reported from users that tried to run BRAKER with AUGUSTUS releases maintained by third parties, i.e. Bioconda.
`

version is a little ambiguous, release or development tree?  It sounds like what Braker really wants is the latter, from here:

https://github.com/Gaius-Augustus/Augustus.git

which has changes post 3.3.3.  

Perhaps modify the installation instructions, or push 3.3.4 which includes the needed changes?  

I suspect that I am not the only one who prefers to install a "release" from github rather than using "git clone", in the (perhaps vain) hope that a release is more thoroughly debugged than the code which is still being developed.

**Comment by mathog** [comment] 2020-07-31 21:30
Replacing the one perl file let test1.sh complete.  However...

```
/test2.sh
#SNIP many lines
# Fri Jul 31 14:17:24 2020: Trying to guess $DIAMOND_PATH from location of diamond executable that is available in your $PATH
# Fri Jul 31 14:17:24 2020: Setting $DIAMOND_PATH to /usr/common/modules/el8/x86_64/software/diamond/0.9.32-CentOS-vanilla/bin
# Fri Jul 31 14:17:24 2020: Did not find environment variable $ALIGNMENT_TOOL_PATH (either variable does not exist, or the path given in va
riable does not exist). Will try to set this variable in a different way, later.
# Fri Jul 31 14:17:24 2020: ERROR: in file /usr/common/modules/el8/x86_64/software/braker/3.0-CentOS-vanilla/scripts/braker.pl at line 2563
$ALIGNMENT_TOOL_PATH not set!
This is an obligatory argument if you provided protein sequence file(s).
There are 3 alternative ways to set this variable for
 braker.pl:
   a) provide command-line argument
      --ALIGNMENT_TOOL_PATH=/your/path
   b) use an existing environment variable
      $ALIGNMENT_TOOL_PATH for setting the environment
      variable, run
           export ALIGNMENT_TOOL_PATH=/your/path
      in your shell. You may append this to your .bashrc
      or .profile file in order to make the variable
      available to all your bash sessions.
   c) braker.pl can try guessing the location of
      $ALIGNMENT_TOOL_PATH from the location an alignment
      tool executable (corresponding to the alignment tool
      given by command line argument --prg=yourTool (in
      this case ) that is available in your $PATH
      variable.
      If you try to rely on this option, you can check by
      typing
           which gth
               or
           which exonerate
               or
           which spaln
      in your shell, whether there is an alignment tool
      executable in your $PATH

#but all 3 are defined
which gth
~/el8/x86_64/software/genomethreader/1.7.1-CentOS-vanilla/bin/gth
which exonerate
~/el8/x86_64/software/exonerate/2.4.0-CentOS-vanilla/bin/exonerate
which spaln
~/el8/x86_64/software/spaln/2.4.0-CentOS-vanilla/bin/spaln
echo $ALIGNMENT_TOOL_PATH
#nothing

```

I do not see any evidence that test2.sh takes arguments.  That active part of test2.sh is

` braker.pl --genome=../genome2.fa --prot_seq=../proteins2.fa --epmode --softmasking --workingdir=$wd --cores=8 --gm_max_intergenic 1000
`
which does not have --prg argument.  So what is wrong here, test2.sh needs ALIGNMENT_TOOL_PATH defined before it will run?  Is there some reason braker.pl does not check  those 3 binaries and pick one based on a default preference order?

Thanks.

**Comment by mathog** [comment] 2020-07-31 22:59
Still having problems:

```
export ALIGNMENT_TOOL_PATH=/home/common/modules/el8/x86_64/software/exonerate/2.4.0-CentOS-vanilla/bin
./test2.sh

#fails at:

# Fri Jul 31 15:39:47 2020: starting prothint.py
/home/common/modules/el8/x86_64/software/exonerate/2.4.0-CentOS-vanilla/bin/prothint.py --threads=8 --geneMarkGtf /home/common/src/braker/example/tests/test2/GeneMark-ES/genemark.gtf /home/common/src/braker/example/tests/test2/genome.fa /home/common/src/braker/example/tests/test2/proteins.fa
```
because it merged the ALIGNMENT_TOOL_PATH with prothint.py to create a hybrid which does not correspond to prothint.py's location.  It is on PATH though.

```
 which prothint.py
~/el8/x86_64/software/prothint/2.4.0-CentOS-vanilla/bin/prothint.py

```

**Comment by tomasbruna** [comment] 2020-08-03 03:54
Hello @mathog,

Thank you for your suggestions about improving the installation instructions. The best solution would indeed be to make a new AUGUSTUS release, I think it is coming soon, but it is out of my hands. Right now, I will update the README file to be more clear.

About issues with test2.sh -- I am currently rewriting the whole part of BRAKER2 related to proteins. In this update, these issues will be fixed. You can try the code in branch https://github.com/Gaius-Augustus/BRAKER/tree/ep-cleanup or wait a couple more days until it is finished, properly tested, and merged into master.

Tomas

**Comment by tomasbruna** [comment] 2020-08-07 20:20
Please try the latest BRAKER version, all the test problems should be fixed.

**Comment by mathog** [comment] 2020-08-07 22:32
Still problems.

```
#reinstalled, remade module for braker
module load braker
module list
Currently Loaded Modules:
  1) CentOS/vanilla                       5) samtools/1.10-CentOS-vanilla          9) ncbi-toolbox-cpp/2.10.1-CentOS-vanilla  13) prothint/2.4.0-CentOS-vanilla
  2) augustus/3.3.3-CentOS-vanilla        6) genomethreader/1.7.1-CentOS-vanilla  10) diamond/0.9.32-CentOS-vanilla           14) braker/3.0-CentOS-vanilla
  3) genemark_suite/4.59-CentOS-vanilla   7) spaln/2.4.0-CentOS-vanilla           11) cdbtools/0.982-CentOS-vanilla
  4) bamtools/2.5.1-CentOS-vanilla        8) exonerate/2.4.0-CentOS-vanilla       12) biopython/1.77-CentOS-vanilla
#verified that  command:
#   gmes_petap.pl --seq ../input/genome.fasta --EP --dbep ../input/proteins.fasta --verbose --cores=8 --max_intergenic 10000
#runs in /usr/common/src/gmes_linux_64/GeneMark-E-tests/EP/, so .gm_key must be OK
cd /usr/common/src/braker/example
wget http://topaz.gatech.edu/GeneMark/Braker/RNAseq.bam
md5sum RNAseq.bam
f37620e5342f1364c2057518880293ac  RNAseq.bam
cd tests
./test2.sh
#fails
tail test2.log
[Fri Aug  7 15:21:51 2020] Output processed
[Fri Aug  7 15:21:51 2020] ProtHint finished.
ERROR in file /usr/common/modules/el8/x86_64/software/braker/3.0-CentOS-vanilla/scripts/braker.pl at line 6407
Failed to execute: perl /usr/common/modules/el8/x86_64/software/genemark_suite/4.59-CentOS-vanilla/gmes_petap.pl --verbose --seq /home/common/src/braker/example/tests/test2/genome.fa --EP /home/common/src/braker/example/tests/test2/genemark_hintsfile.gff --cores=8  --gc_donor 0.001 --evidence /home/common/src/braker/example/tests/test2/genemark_evidence.gff  --soft_mask auto --max_intergenic=10000 1>/home/common/src/braker/example/tests/test2/GeneMark-EP.stdout 2>/home/common/src/braker/example/tests/test2/errors/GeneMark-EP.stderr
Failed to execute: perl /usr/common/modules/el8/x86_64/software/genemark_suite/4.59-CentOS-vanilla/gmes_petap.pl --verbose --seq /home/common/src/braker/example/tests/test2/genome.fa --EP /home/common/src/braker/example/tests/test2/genemark_hintsfile.gff --cores=8  --gc_donor 0.001 --evidence /home/common/src/braker/example/tests/test2/genemark_evidence.gff  --soft_mask auto --max_intergenic=10000 1>/home/common/src/braker/example/tests/test2/GeneMark-EP.stdout 2>/home/common/src/braker/example/tests/test2/errors/GeneMark-EP.stderr
The most common problem is an expired or not present file ~/.gm_key!

real    4m58.561s
user    11m12.055s
sys     1m9.350s
tar -cf - test2 test2.log | gzip -c >/tmp/test2.tar.gz

```
[test2.tar.gz](https://github.com/Gaius-Augustus/BRAKER/files/5044061/test2.tar.gz)

.gm_key is definitely there and gmes_petap.pl does run, at least for their test.

**Comment by tomasbruna** [comment] 2020-08-07 23:13
Hi @mathog,

I forgot to mention that I also released a new version of ProtHint, my bad! The new BRAKER code depends on the new release, please get it from https://github.com/gatech-genemark/ProtHint/releases/tag/v2.5.0.

Sorry about this, let me know if the test works with the fix.

Best,
Tomas

**Comment by mathog** [comment] 2020-08-07 23:21
Will get the new ProtHint shortly after test1 finishes (one way or the other).  It has been running for a while and seems to be OK so far.

If BRAKER is going to be finicky about which software releases it needs would be a good idea for it to check version numbers right at the start and if it finds a problem exit with:

`This version of BRAKER requires ProtHINT 2.5.0 or higher`

rather than running and failing with a mysterious error message.  Doing that will in the end be less work for everybody involved.

Thanks.

**Comment by tomasbruna** [comment] 2020-08-07 23:26
Good point, we will implement such checks.

**Comment by mathog** [comment] 2020-08-08 01:03
test1.sh and test2.sh finished, test3.sh is running.  Progress.

Is there a comparison tool of some sort for determining if the results are as expected?  

The contents of the files in results/test[12] do not diff trivially with the files in tests/test[12].

**Comment by tomasbruna** [comment] 2020-08-10 14:45
Hi @mathog,

sure, you can use this script https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/compare_intervals_exact.pl. I'll add this info to the readme file about tests.

The usage is:

* To compare on the coding exon level:
````
compare_intervals_exact.pl --f1 augustus.hints.gtf --f2 ../../results/test2/augustus.hints.gtf --verbose
````
* To compare on the gene level:
````
compare_intervals_exact.pl --f1 augustus.hints.gtf --f2 ../../results/test2/augustus.hints.gtf --gene -verbose
````

Best,
Tomas

**Comment by mathog** [comment] 2020-08-10 17:37
Close, but not exactly the same.  Reviewed installation and the only discrepancy I see is that the "tested with" list says "Augustus 3.3.4" but 3.3.3 is installed here.  (There is no 3.3.4 under "releases".  The script filterGenesIn_mRNAname.pl was copied in from github and layered over 3.3.3, which was, as far as I knew, the only difference needed to make this Augustus 3.3.3 work with BRAKER).  Are the results below expected (from random number generator seed or thread scheduling induced variation) or should these have matched exactly?

```
compare_intervals_exact.pl --f1 test2/augustus.hints.gtf --f2 ../results/test2/augustus.hints.gtf --verbose
# CDS in file test2/augustus.hints.gtf: 1446
# CDS in file ../results/test2/augustus.hints.gtf: 1454

#in     match   unique  %match  CDS

1446    1425    21      98.55   test2/augustus.hints.gtf
1454    1425    29      98.01   ../results/test2/augustus.hints.gtf

compare_intervals_exact.pl --f1 test2/braker.gtf --f2 ../results/test2/braker.gtf --verbose 
# CDS in file test2/braker.gtf: 1456
# CDS in file ../results/test2/braker.gtf: 1463

#in     match   unique  %match  CDS

1456    1435    21      98.56   test2/braker.gtf
1463    1435    28      98.09   ../results/test2/braker.gtf

compare_intervals_exact.pl --f1 test2/augustus.hints.gtf --f2 ../results/test2/augustus.hints.gtf --gene -verbose
# Transcripts-CDS in file test2/augustus.hints.gtf: 295
# After removal of duplications:
# Transcripts-CDS in file test2/augustus.hints.gtf: 295
# Transcripts-CDS in file ../results/test2/augustus.hints.gtf: 297
# After removal of duplications:
# Transcripts-CDS in file ../results/test2/augustus.hints.gtf: 297
# transc-per-gene hist
# 1 279
# 2 8
# transc-per-gene hist
# 1 279
# 2 9

#in     match   unique  %       Gene-CDS

287     274     13      95.47   test2/augustus.hints.gtf
274     274     0       100.00  ../results/test2/augustus.hints.gtf

```

**Comment by tomasbruna** [comment] 2020-08-10 17:49
Hello @mathog,

small variations are expected, as mentioned here https://github.com/Gaius-Augustus/BRAKER#data-description.

We've tried to reduce this stochasticity be fixing the random seeds etc. but some tools still produce slightly different results, depending on the hardware used and/or their specific version (for example DIAMOND can slightly differ between versions).

Just out of curiosity, can you compare the `hintsfile.gff` (use the `--intron` option in the compare script) and `genemark.gtf` in the `GeneMark-EP` folder?

Thanks,
Tomas

**Comment by mathog** [comment] 2020-08-10 18:01
I am just trying to determine if the variation observed is within that expected for "may not be exactly identical".  


Is this the comparison you wanted?

```
compare_intervals_exact.pl --f1 test2/GeneMark-EP/genemark.gtf --f2 test2/augustus.hints.gtf --intron -verbose
# Introns in file test2/GeneMark-EP/genemark.gtf: 1184
# Introns in file test2/augustus.hints.gtf: 1162

#in     match   unique  %       Intron

1184    0       1184    0.00    test2/GeneMark-EP/genemark.gtf
1162    0       1162    0.00    test2/augustus.hints.gtf

```

**Comment by tomasbruna** [comment] 2020-08-10 18:17
> I am just trying to determine if the variation observed is within that expected for "may not be exactly identical".

The variation you are observing is definitely within the expected range.

> this the comparison you wanted?

Not quite, I was looking for the comparison with the reference results for the two files. Like this:

```
# For hinstfile.gff
compare_intervals_exact.pl --f1 ../results/test2/hintsfile.gff --f2 test2/hintsfile.gff --intron --verbose
# For genemark.gtf
compare_intervals_exact.pl --f1 ../results/test2/genemark.gtf --f2 test2/GeneMark-EP/genemark.gtf --verbose
```

Sorry for not being more clear on that.

**Comment by mathog** [comment] 2020-08-10 20:53
No problem.

```
compare_intervals_exact.pl --f1 ../results/test2/hintsfile.gff --f2 test2/hintsfile.gff --intron --verbose
# Introns in file ../results/test2/hintsfile.gff: 1131
# Introns in file test2/hintsfile.gff: 1129

#in     match   unique  %       Intron

1131    1129    2       99.82   ../results/test2/hintsfile.gff
1129    1129    0       100.00  test2/hintsfile.gff

compare_intervals_exact.pl --f1 ../results/test2/genemark.gtf --f2 test2/GeneMark-EP/genemark.gtf --verbose
# CDS in file ../results/test2/genemark.gtf: 1461
# CDS in file test2/GeneMark-EP/genemark.gtf: 1461

#in     match   unique  %match  CDS

1461    1461    0       100.00  ../results/test2/genemark.gtf
1461    1461    0       100.00  test2/GeneMark-EP/genemark.gtf

```

**Comment by tomasbruna** [comment] 2020-08-12 14:26
Thanks a lot! The small difference in hints found is likely the cause for a slightly different result.

**Closed** 2020-09-07 16:40 UTC
