### ISSUE TITLE
An error of stringtie2utr.py

### ISSUE THREAD

**Issue by YouxinZhao** [Gaius-Augustus/BRAKER#735] opened 2024-01-04 09:35 UTC
stringtie2utr.py -g braker.gtf  -s /braker/GeneMark-ETP/rnaseq/stringtie/transcripts_merged.gff  -o x.gtf

The result of x.gtf generated a new sequence name (tep391541zz) that does not belong to my genome. 
![图片](https://github.com/Gaius-Augustus/BRAKER/assets/95477328/4bf270df-79b9-4105-b55e-8158d7958e1b)
The name should be "tep2541zz" according to transcripts_merged.gff
I am using efficient braker3 to annotate the genomes of multiple species, and I really hope this problem can be solved

**Comment by YouxinZhao** [comment] 2024-01-04 09:38
The result of transcripts_merged.gff
![图片](https://github.com/Gaius-Augustus/BRAKER/assets/95477328/d1ef1004-0feb-46c9-a095-ed3cf417b988)

**Comment by KatharinaHoff** [comment] 2024-01-04 11:30
Thank you, that looks like a real bug.

I have tested the stringtie2utr script on 8 genomes and cannot reproduce the problem with these genomes. If possible, please share the input data to the script with me so that I can look into it. My e-mail is katharina.hoff at uni-greifswald.de in case you want to share a link.

**Comment by KatharinaHoff** [comment] 2024-01-05 09:36
Thank you for sharing the data, I can reproduce the problem. That's a start.

**Comment by KatharinaHoff** [comment] 2024-01-05 13:09
I found the problem. I replace coordinates at some point, and your sequence names have numbers. That's not the case to that extent in my own data sets. I will fix it.

**Comment by KatharinaHoff** [comment] 2024-01-05 13:17
Fixed in commit https://github.com/Gaius-Augustus/BRAKER/commit/a3d1f385d7bce4743ca295651c095ce75db86343

**Closed by KatharinaHoff** 2024-01-05 13:17 UTC
Labels: bug
