### ISSUE TITLE
problem on an expired or not present file ~/.gm_key!

### ISSUE THREAD

**Issue by Jiangjiangzhang6** [Gaius-Augustus/BRAKER#512] opened 2022-08-14 07:48 UTC
Dear friends
when I run the braker2, its show th error like this 

![image](https://user-images.githubusercontent.com/101324838/184527443-c7c83bfd-99e9-4432-b676-2f983a3b95b4.png)

ERROR in file /public/home/zhaoli/software/anaconda3/envs/braker2/bin/braker.pl at line 6656
Failed to execute: perl /public/home/software/opt/bio/software/GeneMark_ES/4.68/gmes_petap.pl --verbose --sequence=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genome.fa --ET=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genemark_hintsfile.gff --cores=10 --gc_donor 0.001 1>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/GeneMark-ET.stdout 2>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/errors/GeneMark-ET.stderr
Failed to execute: perl /public/home/software/opt/bio/software/GeneMark_ES/4.68/gmes_petap.pl --verbose --sequence=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genome.fa --ET=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genemark_hintsfile.gff --cores=10 --gc_donor 0.001 1>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/GeneMark-ET.stdout 2>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/errors/GeneMark-ET.stderr
The most common problem is an expired or not present file ~/.gm_key!

but it would run and down when run de commads :/public/home/software/opt/bio/software/GeneMark_ES/4.68/gmes_petap.pl --verbose --sequence=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genome.fa --ET=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genemark_hintsfile.gff --cores=10 --gc_donor 0.001 1>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/GeneMark-ET.stdout 2>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/errors/GeneMark-ET.stderr

and the command : perl /public/home/software/opt/bio/software/GeneMark_ES/4.68/gmes_petap.pl --verbose --sequence=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genome.fa --ET=/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/genemark_hintsfile.gff --cores=10 --gc_donor 0.001 1>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/GeneMark-ET.stdout 2>/public/home/zhaoli/dama/annotation/hap1/rna-seq/braker/braker/errors/GeneMark-ET.stderr

its error when run the braker.pl

thank you for your help

**Comment by tomasbruna** [comment] 2022-08-18 22:45
Closing as the problem is also discussed in https://github.com/Gaius-Augustus/BRAKER/issues/475

**Closed by tomasbruna** 2022-08-18 22:45 UTC
