### ISSUE TITLE
Using BRAKER with translation table 4

### ISSUE THREAD

**Issue by msinghgb** [Gaius-Augustus/BRAKER#148] opened 2020-01-13 15:48 UTC
I am trying to use BRAKER for a genome which is translated through translation table 4.
Since BRAKER currently does not accept translation table 4 as an option, what would you recommend as a solution for this?
Are there any changes which I can directly make in the BRAKER script to make this work?

**Comment by KatharinaHoff** [comment] 2020-02-20 20:25
The problem is that we currently cannot switch the translation table for GeneMark in BRAKER.

I will close this issue because we have another open issue about this at https://github.com/Gaius-Augustus/BRAKER/issues/3

**Closed by KatharinaHoff** 2020-02-20 20:25 UTC
