### ISSUE TITLE
joingenes segmentation fault

### ISSUE THREAD

**Issue by ChuShin** [Gaius-Augustus/BRAKER#229] opened 2020-06-17 17:33 UTC
Hello,
We ran into a segmentation fault error in joingenes while running braker pipeline(v2.1.5, augustus 3.3.3). I extracted the first offending lines (see below a.gtf) and I can reproduce the error in terminal (see log below). Please can you help?

Thanks.

`joingenes --genesets=a.gtf,a.gtf --priorities=2,1 --output=output.gtf`
\# After loading a.gtf (Priority 2) there are 2 transcripts in transcript list.
\# After loading a.gtf (Priority 1) there are 4 transcripts in transcript list.
Segmentation fault

and a.gtf attached below:

Scaffold01577	AUGUSTUS	gene	26249	28343	0.8	+	.	g160845
Scaffold01577	AUGUSTUS	transcript	26249	28343	0.44	+	.	g160845.t1
Scaffold01577	AUGUSTUS	start_codon	26249	26251	.	+	0	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	26249	27341	1	+	0	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	26249	27341	.	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	intron	27342	27405	0.49	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	27406	27929	0.48	+	2	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	27406	27929	.	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	intron	27930	28004	0.99	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	28005	28112	0.99	+	0	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	28005	28112	.	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	intron	28113	28189	0.99	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	28190	28290	0.9	+	0	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	28190	28290	.	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	intron	28291	28343	0.9	+	.	transcript_id "g160845.t1"; gene_id "g160845";
Scaffold01577	AUGUSTUS	transcript	26249	27983	0.36	+	.	g160845.t2
Scaffold01577	AUGUSTUS	start_codon	26249	26251	.	+	0	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	26249	27341	1	+	0	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	26249	27341	.	+	.	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	intron	27342	27405	0.5	+	.	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	CDS	27406	27983	0.36	+	2	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	exon	27406	27983	.	+	.	transcript_id "g160845.t2"; gene_id "g160845";
Scaffold01577	AUGUSTUS	stop_codon	27981	27983	.	+	0	transcript_id "g160845.t2"; gene_id "g160845";

**Comment by tomasbruna** [comment] 2020-08-12 14:50
Hello @ChuShin,

I tried to reproduce the error on 3 different systems, unfortunately, I could not reproduce the segmentation fault, the binary worked correctly each time.

Does it fail like this on all inputs you supply? Can you try to re-compile `joingenes`, or run it on a different machine?

Tomas

**Comment by ricardo-aaron** [comment] 2020-08-13 23:37
I also get that error:
Thu Aug 13 15:35:07 2020: Log information is stored in file /elpool/rchavez/Selaginella/sello/braker/braker_run1/braker.log
ERROR in file /elpool/software/BRAKER/scripts/braker.pl at line 9472
Failed to execute: /elpool/software/Augustus/bin/joingenes --genesets=/elpool/rchavez/Selaginella/sello/braker/braker_run1/augustus.E.gtf,/elpool/rchavez/Selaginella/sello/braker/braker_run1/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=/elpool/rchavez/Selaginella/sello/braker/braker_run1/join.gtf 1> /dev/null 2> /elpool/rchavez/Selaginella/sello/braker/braker_run1/errors/joingenes.err!

joingenes.err contains:
Segmentation fault (core dumped)

this is the output of the joingenes command:
After loading /elpool/rchavez/myspecies/sello/braker/braker_run1/augustus.E.gtf (Priority 2) there are 24205 transcripts in transcript list.
After loading /elpool/rchavez/myspecies/sello/braker/braker_run1/augustus.Ppri5.gtf_filtered (Priority 1) there are 24205 transcripts in transcript list.
Segmentation fault (core dumped)

This with an Augustus git cloned today.

**Comment by KatharinaHoff** [comment] 2020-08-14 08:12
@ChuShin thank you very much for creating a toy example data set. I am able to reproduce the Segmentation fault. Someone in our group will eventually look into this.
Katharina

**Comment by MarioStanke** [comment] 2020-08-14 09:56
It is now an issue in the Augustus repository as joingenes belongs there:
https://github.com/Gaius-Augustus/Augustus/issues/182

**Comment by bioinfowheat** [comment] 2020-09-18 07:39
I'm also having this problem with the latest version of BRAKER2

# error on run 
[Thu Sep 17 15:49:26 2020] Enqueueing pair 329050/329379 (99.9%). Est. time left: 00:00:02 (hh:mm:ss)                                                        
[Thu Sep 17 15:50:28 2020] 329379/329379 (100%) pairs aligned
[Thu Sep 17 15:50:28 2020] Alignment of pairs finished
[Thu Sep 17 15:50:28 2020] Translating coordinates from local pair level to contig level
[Thu Sep 17 15:50:50 2020] Finished spliced alignment
[Thu Sep 17 15:50:51 2020] Processing the output
[Thu Sep 17 15:52:35 2020] Output processed
[Thu Sep 17 15:52:35 2020] ProtHint finished.
ERROR in file /data/programs/BRAKER2_v2.1.5/scripts/braker.pl at line 9481
Failed to execute: /data/programs/Augustus_v3.3.3/bin/joingenes --genesets=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.E.gtf,/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/join.gtf 1> /dev/null 2> /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err!

# OK, check the error file
more /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err
Load warning: Did not expect feature "internal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "s
tart_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "initial". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "st
art_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "terminal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "s
tart_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Segmentation fault


# OK, so I am attempting to run this
/data/programs/Augustus_v3.3.3/bin/joingenes --genesets=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.E.gtf,/mnt/griffin/marcel/Pca_genome/braker2_test/braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=/mnt/griffin/marcel/Pca_genome/braker2_test/braker/join.gtf 1> /dev/null 2> /mnt/griffin/marcel/Pca_genome/braker2_test/braker/errors/joingenes.err
# returns
Segmentation fault

**Comment by JudithR** [comment] 2021-02-20 08:28
Hi,
Not sure whether this should go with BRAKER or Augustus. I posted it on Augustus as issue #260.
Joingenes clearly is part of Augustus, but the 'faulty' input is generated by BRAKER.

I'm running BRAKER with --etpmode
`braker.pl --species=mySpecies --genome=myGenome_softmasked.fa --softmasking --bam=myGenome_STARAligned.sortedByCoord.out.noMito.fwd.bam,myGenome_STARAligned.sortedByCoord.out.noMito.rev.bam --UTR=on --cores=10 --stranded=+,- --prothints=prothint_augustus.gff --hints=hintsfile.gff --etpmode`

The hintsfile.gff is from a previous BRAKER run (RNAseq only) without etpmode and OrthoDB, but otherwise identical.

I encountered issue #182 and subsequently upgraded Augustus to the latest git-checkout. Unfortunately the seqfault still occurs.
The offending joingenes command is:
`joingenes --genesets=braker/augustus.E.gtf,braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=braker/join.gtf 1> /dev/null 2> braker/errors/joingenes.err`

This issue was only present in BRAKER 2.5, but is resolved in the latest BRAKER checkout.

I reran the job with both the latest BRAKER and Augustus checkouts.

There a similar issue seems to occur in a different step and not the same as mentioned above:
`ERROR in file /mnt/scratch/risse001/software/BRAKER/scripts/braker.pl at line 9760`

This is the tail of the logfile
`# File braker/augustus.Ppri5.gtf has 31546 supported transcripts, braker/augustus.E.gtf has 42337 supported transcripts
# Filtering those genes that have evidence by src=P from braker/augustus.Ppri5.gtf...
perl filter_augustus_gff.pl --in=braker/augustus.Ppri5.gff --src=P --out=braker/augustus.Ppri5.gtf_filtered
joingenes --genesets=braker/augustus.E.gtf,braker/augustus.Ppri5.gtf_filtered --priorities=2,1 --output=braker/join.gtf 1> /dev/null 2> /local_scratch/risse001/Taraxacum/braker/braker/errors/joingenes.err`

The joingenes error log only gives warnings about unknown features prior to the segfault.
`Load warning: Did not expect feature "terminal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "internal". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.
Load warning: Did not expect feature "initial". Known features are "CDS", "UTR", "3'-UTR", "5'-UTR", "exon", "intron", "gene", "transcript", "tss", "tts", "start_codon" and "stop_codon". This feature is going to be ignored.
This warning may affect the result.`

But this time both input files do contain data..

I'm not sure how to quickly fix this
If you could help, that would be greatly appreciated. Also what would be the fastest way to continue the BRAKER run?
Regards
Judith

**Comment by JudithR** [comment] 2021-02-26 11:29
No longer relevant. The latest git checkout from Augustus does not give the error anymore. Somehow joingenes did not get recompiled with the latest checkout.
Apologies

**Closed** 2022-01-07 12:40 UTC
