### ISSUE TITLE
Braker failed due to no genemark_hintsfile.gff.rnaseq.tmp file

### ISSUE THREAD

**Issue by mudithekanayake** [Gaius-Augustus/BRAKER#454] opened 2022-01-24 20:13 UTC
Hello,

I am running Braker 2.1.6 using the following command and it get failed everytime at the same point.

`( time braker.pl --GENEMARK_PATH=/home/mudith/.conda/envs/braker2.1.6/share/gmes_linux_64 --genome=flye_canu_nextpolish_pd_cleaned.fa.masked --prot_seq=all.blastp.tophit.no_bac_arc_virus.list.fasta,UP000007879_400682.fasta --prg=gth --bam=alignments.hisat2.bam --softmasking --workingdir=$wd --cores 8) &> braker_rseq_protein.log`

I was running Braker using the same command and same RNAseq and protein sequences throughout the last year and I last ran it successfully month ago on 17th December 2021. However for some reason now I'm getting the following error in the log file.

```
mv: cannot stat ‘/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff.rnaseq.tmp’: No such file or directory
ERROR in file /home/mudith/.conda/envs/braker2.1.6/bin/braker.pl at line 6295
Failed to execute: mv /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff.rnaseq.tmp /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gf
```

My Braker.log file looks like this.

```
# Mon Jan 24 12:48:40 2022: Deleting SAM header file /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/alignments_header.sam (will not be needed from here on)
# Mon Jan 24 12:48:40 2022: Deleting /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/alignments_new_header.sam
# Mon Jan 24 12:48:40 2022: make hints from BAM file /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/alignments.hisat2.bam
/home/mudith/.conda/envs/braker2.1.6/bin//bam2hints --intronsonly --in=/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/alignments.hisat2.bam --out=/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/bam2hints.temp.0.gff 1> /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/errors/bam2hints.0.stdout 2>/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/errors/bam2hints.0.stderr
# Mon Jan 24 13:13:29 2022: add hints from BAM file /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/alignments.hisat2.bam to hints file
cat /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/bam2hints.temp.0.gff >>/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.temp.gff
# Mon Jan 24 13:13:30 2022: Checking for hints of src=C and with grp tags that should not be joined according to multiplicity
# Mon Jan 24 13:13:31 2022: Joining hints that are identical (& from the same source) into multiplicity hints (input file /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/tmp_merge_hints.gff)
# Mon Jan 24 13:13:31 2022: sort hints of type rnaseq
cat /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/tmp_merge_hints.gff | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -n -k 3,3 | sort -s -k 1,1 >/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hints.rnaseq.temp.sort.gff
# Mon Jan 24 13:13:36 2022: join multiple hints
perl /work/LAS/dlavrov-lab/dlavrov-lab/mudith/envs/braker2.1.6/bin/join_mult_hints.pl </work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hints.rnaseq.temp.sort.gff >/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/tmp_merge_hints.gff 2>/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/errors/join_mult_hints.rnaseq.stderr
mv /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/tmp_merge_hints.gff /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.temp.gff
# Mon Jan 24 13:13:38 2022: filter introns, find strand and change score to 'mult' entry
perl /work/LAS/dlavrov-lab/dlavrov-lab/mudith/envs/braker2.1.6/bin/filterIntronsFindStrand.pl /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genome.fa /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.temp.gff --score 1>>/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.gff 2>/work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/errors/filterIntronsFindStrand.stderr
# Mon Jan 24 13:13:40 2022: rm /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.temp.gff
# Mon Jan 24 13:13:40 2022: Preparing hints for running GeneMark
# Mon Jan 24 13:13:40 2022: Filtering intron hints for GeneMark from /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/hintsfile.gff...
cat /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff.prot | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /work/LAS/dlavrov-lab/dlavrov-lab/mudith/envs/braker2.1.6/bin/join_mult_hints.pl > /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff.prot.tmp
mv /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff.rnaseq.tmp /work/LAS/dlavrov-lab/dlavrov-lab/mudith/project_niphates/braker/19th_run_flyecanu_nextpolish_pd_cleaned_amphi_nipha_rseq/braker_rseq_protein/genemark_hintsfile.gff
```

I will be really grateful if you can help me with this issue. I have attached the complete Braker.log file below.
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/7928558/braker.log)

**Comment by tomasbruna** [comment] 2022-03-01 22:18
Hi @mudithekanayake,

this is strange, I don't think there were any changes related to this since December 17th, 2021. Can you reproduce this error on the example input [test5.sh](https://github.com/Gaius-Augustus/BRAKER/blob/master/example/tests/test5.sh)?

Also, please know that GenomeThreader (`--prg=gth`) is no longer actively supported in BRAKER. I'd suggest using the newly developed [TSEBRA](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04482-0) to combine RNA-Seq and proteins in BRAKER.

Tomas

**Comment by dirkjanvw** [comment] 2022-03-18 15:18
Hi,

I get the exact same error @mudithekanayake reports above. However, I have not got my dataset to work with BRAKER before. Also, I tested the test5.sh script with --hints and that runs successfully. What could be the reason?

I ran BRAKER as follows (since I was planning to use it for TSEBRA):
```bash
braker.pl --genome=genome.fa.masked --hints=bam2hints.gff --gff3 --cores=8 --softmasking --workingdir=braker1_out
```

**Comment by tomasbruna** [comment] 2022-05-02 21:37
Hi @dirkjanvw,

errors like this usually occur when some components (or BRAKER itself) are not updated to their latest version.

If you are working with the latest version, please share your full BRAKER log, I will take a look and try to see what happened.

Best,
Tomas

**Comment by Lcornet** [comment] 2022-05-04 08:08
I have the same error too:

cat /scratch/users/l/c/lcornet/jerusalem/Annotation/work/1e/f2e1143e7446e6ec71c80873264336/braker1_out/genemark_hintsfile.gff.prot | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /opt/Augustus/scripts/join_mult_hints.pl > /scratch/users/l/c/lcornet/jerusalem/Annotation/work/1e/f2e1143e7446e6ec71c80873264336/braker1_out/genemark_hintsfile.gff.prot.tmp
mv /scratch/users/l/c/lcornet/jerusalem/Annotation/work/1e/f2e1143e7446e6ec71c80873264336/braker1_out/genemark_hintsfile.gff.rnaseq.tmp /scratch/users/l/c/lcornet/jerusalem/Annotation/work/1e/f2e1143e7446e6ec71c80873264336/braker1_out/genemark_hintsfile.gff

My CMD:
        braker.pl --genome=genome.fna --prot_seq=GCA_002287475.2.faa \
        --prg=exonerate --cores=20  \
        --workingdir=braker1_out

I join my log.
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/8618696/braker.log)

My install of brake is recent in a singularity, from the singularity file present in an issue of your git.
[braker.def.txt](https://github.com/Gaius-Augustus/BRAKER/files/8618712/braker.def.txt)

**Comment by Lcornet** [comment] 2022-05-06 18:27
Hi,

Thanks, indeed. It was --prg=exonerate. The command that you suggest works fine (as well as test2.sh).

**Comment by crysclitheroe** [comment] 2022-07-20 04:40
Hi There. 
Im having same problem, weirdly in one instance of braker but not another.
Running breaker in a miniconda env on our HPC worked with with the first job I submitted, but all subsequent jobs give the following error after ~6mins in .err:

`cat: /flash/BourguignonU/Crystal/trans_anno/Coptotermes/braker2/genemark_hintsfile.gff.prot.tmp: No such file or directory
ERROR in file /home/c/crystal/miniconda3/envs/braker2-2.1.2/bin/braker.pl at line 4852
Failed to execute: cat /flash/BourguignonU/Crystal/trans_anno/Coptotermes/braker2/genemark_hintsfile.gff.prot.tmp >> /flash/BourguignonU/Crystal/trans_anno/Coptotermes/braker2/genemark_hintsfile.gff`

This is the script use to run:

`source ~/.bashrc
conda activate braker2-2.1.2
ml Other/samtools/1.15.1
ml bamtools/2.5.1

### Data and folders ###
GENUS=Coptotermes
outDir=/flash/BourguignonU/Crystal/trans_anno/${GENUS}/braker2
#soft masked genome
genome=/flash/BourguignonU/Crystal/trans_anno/${GENUS}/softmask/${GENUS}_softmask.fasta.out
RNAbam=/flash/BourguignonU/Crystal/trans_anno/${GENUS}/hisat/${GENUS}_raw_rna_mapped_sorted.bam
protein=/flash/BourguignonU/Crystal/trans_anno/uniprot/uniprot_sprot_invertebrates.dat.gz

### Code ###

mkdir -p ${outdir}

cd ${outdir}

#braker version 
braker.pl       --cores=1 \
                --gff3 \
                --softmasking \
                --species=Coptotermes_rawRNA \
                --genome=${genome} \
                --bam=${RNAbam} \
                --workingdir=/flash/BourguignonU/Crystal/trans_anno/Coptotermes/braker2 \
                --etpmode \
                --prot_seq=${protein}

conda deactivate
`

Is this a conda issue?

**Comment by jdmontenegro** [comment] 2022-07-21 10:40
Hello everyone,
I am getting a similar error with this version of braker. This are the last 10 lines of the log:

```
[Wed Jul 20 18:08:55 2022] Alignment of pairs finished
[Wed Jul 20 18:08:55 2022] Translating coordinates from local pair level to contig level
[Wed Jul 20 18:08:56 2022] Finished spliced alignment
[Wed Jul 20 18:08:56 2022] Flagging top chains
[Wed Jul 20 18:08:56 2022] Processing the output
[Wed Jul 20 18:08:59 2022] Output processed
[Wed Jul 20 18:08:59 2022] ProtHint finished.
cat: /scratch/molevo/jmontenegro/roger/sponge/results/braker2/genemark_hintsfile.gff.rnaseq.tmp: No such file or directory
ERROR in file /apps/braker/2.1.6/scripts/braker.pl at line 6323
Failed to execute: cat /scratch/molevo/jmontenegro/roger/sponge/results/braker2/genemark_hintsfile.gff.rnaseq.tmp /scratch/molevo/jmontenegro/roger/sponge/results/braker2/genemark_hintsfile.gff.prot.tmp > /scratch/molevo/jmontenegro/roger/sponge/results/braker2/genemark_hintsfile.gff
```

my command was the following:

`braker.pl --etpmode --prot_seq=prots.fasta --species=suberites_sp --cores 16 --workingdir=${PWD}/braker2 --AUGUSTUS_CONFIG_PATH=${PWD}/augustus/config --AUGUSTUS_BIN_PATH=/apps/augustus/3.4.0/bin --AUGUSTUS_SCRIPTS_PATH=/apps/augustus/3.4.0/scripts --PROTHINT_PATH=/apps/genemark-es/4.65/ProtHint/bin --genome=genome.fasta --bam=merged.bam`

Any advise what could be going on? 
braker version 2.1.6

**Comment by tomasbruna** [comment] 2022-08-18 22:54
Hello @crysclitheroe and @jdmontenegro,

I'm not sure what's causing the errors, but to circumvent them completely, I recommend using [TSEBRA](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04482-0) to combine RNA-Seq- and protein-based BRAKER runs. It should now work better than running BRAKER in the "--etpmode". Examples can be found at https://github.com/Gaius-Augustus/TSEBRA

Best,
Tomas

**Comment by jdmontenegro** [comment] 2022-08-20 12:43
Thank you Tomas,
 I tried as you suggested and got a warning when running the protein-based braker:
```
#*********
# WARNING:
# The hints file(s) for GeneMark-EX contain less than 150 introns with multiplicity >= 4! (In total, 714 unique introns are contained. 122 have a multiplicity >= 4.)
# Possibly, you are trying to run braker.pl on data that does not provide sufficient multiplicity information. This will e.g. happen if you try to use introns generated from assembled RNA-Seq transcripts; or if you try to run braker.pl in epmode with mappings from proteins without sufficient hits per locus. Or if you use the example data set.
# A low number of intron hints with sufficient multiplicity may result in a crash of GeneMark-EX (it should not crash with the example data set).
#*********
```
I am running it with trembl database, eukary odb10 and ncbi proteins of the closest relatives to my bug. maybe protHints is not relaxed enough? Any suggestion would be more than welcome.

Juan D

**Comment by tomasbruna** [comment] 2022-08-21 02:25
Hi Juan,

how fragmented is your assembly? If it is fragmented (i.e., the contigs are short), this solution could help: https://github.com/Gaius-Augustus/BRAKER/issues/49

Also, are there many introns when using the RNA-Seq-based BRAKER? You can see how many there are by counting introns in the resulting `hintsfile.gff` in the BRAKER folder.

Best,
Tomas

**Comment by jdmontenegro** [comment] 2022-08-21 12:15
The assembly is nearly a chromosome-level assembly, 97% of the assembly is in 23 contigs (15 chromosomes expected), so I would say it's not really fragmented. In the RNAseq run, the hintsfile.gff contains 308,521 intron lines whereas the protein only mode has 32,528, but I still got that warning. Then again, there are plenty of overlapping intron hints in the protein only hintsfile.gff. 
```sca103	ProtHint	intron	65260	65433	2	-	.	src=P;mult=7;pri=4;al_score=0.168198;
sca103	ProtHint	intron	65659	65754	0	-	.	src=P;mult=1;pri=4;al_score=0.129306;
**sca108	ProtHint	intron	394	459	0	+	.	src=P;mult=1;pri=4;al_score=0.146773;
sca108	ProtHint	intron	394	459	1	+	.	grp=398013at33208_41427_0:000ee3_g6379;src=C;pri=4;**
sca109	ProtHint	intron	57613	57708	0	-	.	src=P;mult=1;pri=4;al_score=0.142513;
sca109	ProtHint	intron	69906	70043	2	+	.	src=P;mult=1;pri=4;al_score=0.292053;
sca109	ProtHint	intron	69974	71097	0	+	.	src=P;mult=1;pri=4;al_score=0.103856;
**sca10	ProtHint	intron	1000119	1000256	2	+	.	src=P;mult=7;pri=4;al_score=0.502882;
sca10	ProtHint	intron	1000119	1000256	7	+	.	src=M;mult=7;pri=4**
sca10	ProtHint	intron	1000367	1000532	2	+	.	src=P;mult=5;pri=4;al_score=0.436476;
```
this are just the first ten lines and already 2 duplicate entries. Should I ignore the warning and just work with the tsebra output?

Best regards,

Juan D.

**Comment by tomasbruna** [comment] 2022-08-27 00:25
You can ignore safely ignore the warning, as long as TSEBRA works fine.

The duplicate entries in the protein hintsfile are normal -- notice the difference in the 9th column. This is just a way of passing information between ProtHint and AUGUSTUS.

**Comment by tomasbruna** [comment] 2022-10-11 16:46
Yes, there is actually a work-in-progress protocol for that. Take a look at https://github.com/Gaius-Augustus/BRAKER/blob/long_reads/docs/long_reads/long_read_protocol.md

**Closed** 2022-12-16 15:04 UTC
