### ISSUE TITLE
test1.sh    error

### ISSUE THREAD

**Issue by niexiaoqing** [Gaius-Augustus/BRAKER#234] opened 2020-07-03 07:52 UTC
ERROR: in file /home/xiaoqing/tools/BRAKER/scripts/braker.pl at line 7424
Training gene file in genbank format /home/xiaoqing/tools/BRAKER/example/tests/test1/train.f.gb does not contain any training genes. Possible known cause: no training genes with sufficient extrinsic evidence s
upport or of sufficient length were produced by GeneMark-ES/ET. If you think this is the cause for your problems, consider running BRAKER with different evidence or without any evidence (--esmode) for trainin

how to deal with it??

**Comment by tomasbruna** [comment] 2020-08-03 03:12
Hello,

please check this newer issue to see if this is the same problem https://github.com/Gaius-Augustus/BRAKER/issues/245

Tomas

**Comment by tomasbruna** [comment] 2020-08-07 20:43
I am closing this issue, assuming the cause of this issue was indeed the common problem with older AUGUSTUS script.

**Closed by tomasbruna** 2020-08-07 20:43 UTC
