### ISSUE TITLE
Requesting RNA-seq or hint files when prot_seq is provided

### ISSUE THREAD

**Issue by Lamm-a** [Gaius-Augustus/BRAKER#331] opened 2021-03-04 10:39 UTC
**version** 
```

(base) [robmur@g-12-l0002 primers]$ braker.pl --version
braker.pl version 2.1.5
```

**OS**

```
(base) [robmur@g-12-l0002 primers]$ uname -a
Linux g-12-l0002 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Error**

*Input*
`braker.pl --genome=$input --prot_seq=$protDB --softmasking --workingdir=$outdir --cores=5 --AUGUSTUS_CONFIG_PATH=/home/people/robmur/robmur/programmes/braker/config --AUGUSTUS_BIN_PATH=/services/tools/augustus/3.3.3/bin --AUGUSTUS_SCRIPTS_PATH=/services/tools/augustus/3.3.3/scripts --ALIGNMENT_TOOL_PATH=/services/tools/genomethreader/1.7.3`

I am trying to run Braker2 with only the protein sequences as detailed in your [help docs here](https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance). However I get the following printed for STDERR logs:

```
#**********************************************************************************
#                               BRAKER CONFIGURATION
#**********************************************************************************
# BRAKER CALL: /services/tools/braker2/2.1.5/bin/braker.pl --genome=/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/Micro.fasta --prot_seq=/home/people/robmur/robmur/programmes/braker/db/fungi_proteins.fa --softmasking --workingdir=/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/braker2_output --cores=5 --AUGUSTUS_CONFIG_PATH=/home/people/robmur/robmur/programmes/braker/config --AUGUSTUS_BIN_PATH=/services/tools/augustus/3.3.3/bin --AUGUSTUS_SCRIPTS_PATH=/services/tools/augustus/3.3.3/scripts --ALIGNMENT_TOOL_PATH=/services/tools/genomethreader/1.7.3
# Thu Mar  4 11:29:17 2021: braker.pl version 2.1.5
# Thu Mar  4 11:29:17 2021: Configuring of BRAKER for using external tools...
# Thu Mar  4 11:29:17 2021: Command line flag --AUGUSTUS_CONFIG_PATH was provided. Setting $AUGUSTUS_CONFIG_PATH in braker.pl to /home/people/robmur/robmur/programmes/braker/config.
# Thu Mar  4 11:29:17 2021: Setting $AUGUSTUS_BIN_PATH to command line argument --AUGUSTUS_BIN_PATH value /services/tools/augustus/3.3.3/bin.
# Thu Mar  4 11:29:17 2021: Setting $AUGUSTUS_SCRIPTS_PATH to command line argument --AUGUSTUS_SCRIPTS_PATH value /services/tools/augustus/3.3.3/scripts.
# Thu Mar  4 11:29:17 2021: Found environment variable $GENEMARK_PATH. Setting $GENEMARK_PATH to /services/tools/genemark-es/4.62
# Thu Mar  4 11:29:17 2021: Did not find environment variable $DIAMOND_PATH
# Thu Mar  4 11:29:17 2021: Trying to guess $DIAMOND_PATH from location of diamond executable that is available in your $PATH
# Thu Mar  4 11:29:17 2021: Setting $DIAMOND_PATH to /services/tools/braker2/2.1.5/bin
# Thu Mar  4 11:29:17 2021: Setting $ALIGNMENT_TOOL_PATH to command line argument --ALIGNMENT_TOOL_PATH value /services/tools/genomethreader/1.7.3.
# Thu Mar  4 11:29:17 2021: Did not find environment variable $PYTHON3_PATH
# Thu Mar  4 11:29:17 2021: Trying to guess $PYTHON3_PATH from location of python3 executable that is available in your $PATH
# Thu Mar  4 11:29:17 2021: Setting $PYTHON3_PATH to /services/tools/braker2/2.1.5/bin
# Thu Mar  4 11:29:17 2021: Did not find environment variable $CDBTOOLS_PATH
# Thu Mar  4 11:29:17 2021: Trying to guess $CDBTOOLS_PATH from location of cdbfasta executable that is available in your $PATH
# Thu Mar  4 11:29:17 2021: Setting $CDBTOOLS_PATH to /services/tools/braker2/2.1.5/bin
# Thu Mar  4 11:29:17 2021: ERROR: in file /services/tools/braker2/2.1.5/bin/braker.pl at line 4112
No RNA-Seq or hints file(s) from RNA-Seq specified. Please set at least one RNAseq BAM file or at least one hints file from RNA-Seq (must contain intron hints from src b2h in column 2) to run BRAKER in mode for training from RNA-Seq.
```

Is this intended and then should I just provide my own hints `gff` from `ProtHint`?

Any help would be appreciated.

**Comment by tomasbruna** [comment] 2021-03-04 22:52
Hi @Lamm-a,

please update BRAKER2 code from the master branch here on GitHub, it should work then. A new release is coming soon, but for now, you need to update BRAKER in this way.

Some more suggestions:

* Replace `--ALIGNMENT_TOOL_PATH=/services/tools/genomethreader/1.7.3` with `--PROTHINT_PATH=/your/path/to/ProtHint/bin` (unless you really want to use GenomeThreader, but it is not recommend).
* It seems that you are working with a fungal genome, add a `--fungus` flag for better prediction accuracy.

Best,
Tomas

**Comment by Lamm-a** [comment] 2021-03-05 08:37
Hi @tomasbruna 

Is BRAKER2 v2.1.5 not the most recent? This BRAKER2 was installed 2 days ago, or has a fix been made?

I will defiantly use these other suggestions thanks!

Best
Rob

**Comment by tomasbruna** [comment] 2021-03-06 18:41
Hello Rob,

> Is BRAKER2 v2.1.5 not the most recent? This BRAKER2 was installed 2 days ago, or has a fix been made?

The v2.1.5 is indeed the last big release, but many fixes and changes have been introduced since the release. These changes are only available in the master branch here on GitHub. We are preparing a new release, v2.1.6, which will include all these recent changes.

Tomas

**Comment by Lamm-a** [comment] 2021-03-08 11:07
Thank you I have got that version on the cluster now. Regarding following suggestion:

> Replace `--ALIGNMENT_TOOL_PATH=/services/tools/genomethreader/1.7.3` with `--PROTHINT_PATH=/your/path/to/ProtHint/bin` (unless you really want to use GenomeThreader, but it is not recommend).

When doing this I get errors suggesting it is expecting `--ALIGNMENT_TOOL_PATH=` to be given:
```
# Mon Mar  8 12:00:46 2021: Did not find environment variable $ALIGNMENT_TOOL_PATH (either variable does not exist, or the path given in variable does not exist). Will try to set this variable in a different way, later.
# Mon Mar  8 12:00:46 2021: ERROR: in file /services/tools/braker2/20210304/bin/braker.pl at line 2531
$ALIGNMENT_TOOL_PATH not set!
This is an obligatory argument if you provided protein sequence file(s).
```

**Comment by tomasbruna** [comment] 2021-03-09 02:29
Hello Lamma,

my best guess is that the older version is still somewhere in your environment and it's causing issues. Can you double-check this with?

    which braker.pl

Tomas

**Comment by Lamm-a** [comment] 2021-03-09 09:39
This is the version we are running:

```
(base) [robmur@g-12-l0002 repeatmasker_output]$ which braker.pl
/services/tools/braker2/20210304/bin/braker.pl

```

**Comment by tomasbruna** [comment] 2021-03-10 01:39
Thanks, can you check whether the code in `/services/tools/braker2/20210304/bin/braker.pl` is exactly the same as in this file https://raw.githubusercontent.com/Gaius-Augustus/BRAKER/master/scripts/braker.pl ?

**Comment by tomasbruna** [comment] 2021-03-11 00:08
No, BRAKER does not need a species name. Even if it's given an existing name, it would modify the species parameters in the `species` directory.

Did you check the writing permission for `/home/people/robmur/robmur/programmes/braker/config/species`? What's the output of the following command?

    ls -ld /home/people/robmur/robmur/programmes/braker/config/species

**Comment by Lamm-a** [comment] 2021-03-11 06:49
I have write permissions: 

`drwxr-xr-x 119 robmur ku_00014 3807 Mar 11 07:20 /home/people/robmur/robmur/programmes/braker/config/species`

Some of the genomes are working which is why it is odd only two are not.

**Comment by tomasbruna** [comment] 2021-03-12 00:11
Hello,

thanks for sharing all the log files.

## Problem with the species name

> Some of the genomes are working which is why it is odd only two are not.

Does this problem always occur for these 2 genomes or was it a one-time issue? My best guess is that multiple BRAKERs were running at the same time and they internally assigned the same species name which caused a conflict and this error. If the problem persists, please let me know.

## ProtHint

> There is a lot of error: Alignment is missing after header in the log file also.

These errors can occur in some alignments, but they almost always affect a small minority of the overall set which is being aligned. ProtHint is designed to tolerate these errors. I see in the log you shared that the number of these errors (together with some segmentation faults) is unusually high -- **714**. But this is still only **0.2%** of all alignments ProtHint executed in this run, so it should not be a concern.

> Looking at the prothint output no exons are found, only intron, stop and start codons:
prothint.zip

The prothint.zip you shared (thanks for attaching it) actually looks to be in pretty good shape. No exons should be a part of this output, it only contains exon borders by design. GeneMark does not utilize exon hints, only the exon borders (there is no arrow pointing to GeneMark from CDSparts in [the figure](https://github.com/Gaius-Augustus/BRAKER#braker-with-proteins-of-any-evolutionary-distance)).

AUGUSTUS does, however, utilize the exon hints. Therefore, ProtHint generates a separate output for AUGUSTUS, called `prothint_augustus.gff` which contains exon hints in the format required by AUGUSTUS. You should see this file somewhere in your BRAKER2 run folder.

## No genes in training

I am just double-checking -- did you try to update AUGUSTUS as advised in the warning?
```
# (a) The AUGUSTUS script filterGenesIn_mRNAname.pl is not up-to-date with this version of BRAKER. To solve this issue, either get the latest AUGUSTUS from its master branch with
    git clone git@github.com:Gaius-Augustus/Augustus.git
or download the latest version of filterGenesIn_mRNAname.pl from https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/filterGenesIn_mRNAname.pl and replace the old script in your AUGUSTUS installation folder.
```
We used to get this error a lot and it was always caused by an old AUGUSTUS being used.

Best,
Tomas

**Comment by Lamm-a** [comment] 2021-03-16 10:23
So I updated Augustus and this seems to have solved the issue for some runs as far as I can see they have correct outputs but the `STDERR `still has errors in it:

*semi successful runs*
Contains the following output:
```
augustus.hints.aa
augustus.hints.codingseq
augustus.hints.gff
augustus.hints.gtf
```

[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6147877/braker.zip) for this run

[stderr](https://github.com/Gaius-Augustus/BRAKER/files/6147907/braker2-call.sh.e31161886.zip) for this run

*Runs with no `augustus.hints*` output*

Some runs are working but hitting an error (that seems to be the same as above?) and produce no `augustus.hints*` output
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6148012/braker.zip) for this run

[stderr](https://github.com/Gaius-Augustus/BRAKER/files/6148013/braker2-call.sh.e31161880.zip) for this run

*Completely failed runs*

Some runs are still getting the error mentioned earlier:
```
ERROR in file /services/tools/braker2/20210304/scripts/braker.pl at line 7145
Failed to create new species with new_species.pl, check write permissions in /home/people/robmur/robmur/programmes/braker/config/species directory! Command was perl /home/projects/ku_00014/people/robmur/programmes/braker/augustus_3.4.0/scripts/new_species.pl --species=Sp_2 --AUGUSTUS_CONFIG_PATH=/home/people/robmur/robmur/programmes/braker/config 1> /dev/null 2>/home/projects/ku_00014/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/braker2_output/IC0024/errors/new_species.stderr
```
[braker.log](https://github.com/Gaius-Augustus/BRAKER/files/6148046/braker.zip) for this run

**Comment by tomasbruna** [comment] 2021-03-16 20:55
#### Semi successful runs

These fail when executing the `fix_in_frame_stop_codon_genes.py` script. Please check these issues: https://github.com/Gaius-Augustus/BRAKER/issues/222 or https://github.com/Gaius-Augustus/Augustus/issues/148, maybe the solution to your problem is similar. If this does not solve it, please share the contents of `fix_IFS_log_*` (should be in the BRAKER workdir) and `.../errors/fix_in_frame_stop_codon_genes_augustus.hints.err`.

This script can also be completely skipped by using the `--skip_fixing_broken_genes` flag.

#### Runs with no `augustus.hints*` output

Here I am not sure what happened. From the log, it seems like the script `optimize_augustus.pl` failed -- I have not encoutered this problem before in BRAKER. Please share the logs in `.../braker2_output/IC0032/optimize_augustus.stdout` and `.../braker2_output/IC0032/errors/optimize_augustus.stderr` to get more information about this error.

#### Completely failed runs

What is the content of `.../braker2_output/IC0024/errors/new_species.stderr`?

**Comment by Lamm-a** [comment] 2021-03-16 21:25
*Semi successful runs*

I will try this suggestion in the morning (I am on CET time) but for now here are the requested error files
[fix_in_frame_stop_codon_genes_augustus.hints.err.zip](https://github.com/Gaius-Augustus/BRAKER/files/6152284/fix_in_frame_stop_codon_genes_augustus.hints.err.zip)

*Runs with no `augustus.hints*` output*

The requested logs:
[optimize_augustus.stdout](https://github.com/Gaius-Augustus/BRAKER/files/6152308/optimize_augustus.stdout.zip)

[optimize_augustus.stderr](https://github.com/Gaius-Augustus/BRAKER/files/6152309/optimize_augustus.zip)

*Completely failed runs*

Requested logs:
[new_species.stderr](https://github.com/Gaius-Augustus/BRAKER/files/6152317/new_species.zip)

**Comment by tomasbruna** [comment] 2021-03-16 22:01
Hi @Lamm-a,

thanks for all the logs.

#### Semi successful runs

Looking at the log file, this definitely seems to be the same problem as described in https://github.com/Gaius-Augustus/BRAKER/issues/222 and https://github.com/Gaius-Augustus/Augustus/issues/148. The solutions in those issues should work to fix it.

#### Completely failed runs

The error message is pretty informative: For some reason, BRAKER2 tries to use the species name "Sp_2" but this model already exists. I am not sure why this happens but assigning a custom species name (with `--species UniqueSpeciesName`) for each run should prevent this problem from occurring.

#### Runs with no `augustus.hints*` output

The error causing the crash seems to be `Invalid nucleotide 'È' encountered`. Can you check your input files for some unexpected characters?

Tomas

**Comment by Lamm-a** [comment] 2021-03-18 09:58
*Semi successful runs*
My locales look like this:
(base) [robmur@g-12-l0002 braker2]$ locale
```
LANG=en_US.utf-8
LC_CTYPE="en_US.utf-8"
LC_NUMERIC="en_US.utf-8"
LC_TIME="en_US.utf-8"
LC_COLLATE="en_US.utf-8"
LC_MONETARY="en_US.utf-8"
LC_MESSAGES="en_US.utf-8"
LC_PAPER="en_US.utf-8"
LC_NAME="en_US.utf-8"
LC_ADDRESS="en_US.utf-8"
LC_TELEPHONE="en_US.utf-8"
LC_MEASUREMENT="en_US.utf-8"
LC_IDENTIFICATION="en_US.utf-8"
LC_ALL=en_US.utf-8
```
I am missing the LANGUAGE locale but should LC_ALL not cover that?
Using `--skip_fixing_broken_genes` as expected solved the issue but I would rather not use the flag of course

*Runs with no `augustus.hints*` output*
Ran them again with no changes after checking input file and seeing no special characters and the error did not occur again.

*Completely failed runs*
Suggested fix works

**New issues**

Having rerun with all the suggested changes above, I get a whole bunch of new issues. As far as I can see not a single STDERR shows any errors and indicated that all runs just stopped at prothint. However after inspecting the `braker.logs` it seems the runs all "died" at different spots. None of them timed out, they just stopped. Some stopped on augustus training (leaving logs of augustus hints in the outdir) others on GeneMark.

Here is the outdir structures if it would help to see them:
[outdir_structure.zip](https://github.com/Gaius-Augustus/BRAKER/files/6162871/outdir_structure.zip)

Here are the `braker,logs` for the runs;
[braker_logs.zip](https://github.com/Gaius-Augustus/BRAKER/files/6162874/braker_logs.zip)

From what I can see the logs themselves don't point to any other error logs.

To ensure this is not issues with the local install of braker2 I am using a conda distribution with local installs of GeneMark and Prothint so will edit this with an update.

**Comment by tomasbruna** [comment] 2021-03-18 22:57
#### Semi successful runs

I think the easiest fix was suggested here https://github.com/Gaius-Augustus/Augustus/issues/148#issuecomment-635240604 (the last comment). Configuring the locale can be tricky, please try this first.

#### Runs with no `augustus.hints*` output

> Ran them again with no changes after checking input file and seeing no special characters and the error did not occur again.

Strange, but I'm happy it's resolved.

#### Completely failed runs

> Suggested fix works

Great!

#### New run attempts

> As far as I can see not a single STDERR shows any errors and indicated that all runs just stopped at prothint

This is normal -- ProtHint prints its progress messages to STDERR and the rest of BRAKER2 prints them to `braker.log`. I am planning to unify this, but it's a low priority. As long as the last line of `braker.log` says,
```
#**********************************************************************************
#                               BRAKER RUN FINISHED                                
#**********************************************************************************
```
all is good.

> From what I can see the logs show Braker finishing. What then is the "final" annotation, as in what file should I be using in down stream analysis?

Using `braker.gtf` is the most straightforward but please take a look at https://github.com/Gaius-Augustus/BRAKER#output-of-braker to see what the other outputs represent. The GeneMark-ES and GeneMark-EP+ results are also often very good for fungal genomes, due to a special model triggered by the `--fungus` switch.


> I would just like to really thank you for taking the time to guide me through this as I know it can't be fun :D

You're welcome :) I'm happy we were able to resolve most of the problems in the end.

Tomas

**Comment by Lamm-a** [comment] 2021-03-19 07:36
Would you have any suggestions comparing annotation quality between the different outputs?

**Comment by tomasbruna** [comment] 2021-03-19 23:05
Hi, yes, the `braker.gtf` combines the outputs from different methods. However, it's not a simple union, the results of GeneMark-EP+ are added to AUGUSTUS predictions only if they are fully supported by protein predictions.

To judge the trustworthiness, there are many options. Here I'll give two:

1. To estimate the sensitivity of the gene set (its completeness), you can use [BUSCO](https://busco.ezlab.org/). A simple tutorial is here: https://gatech-genemark.github.io/GeneMark-E-Docs/#/output/evaluation?id=busco-evaluation
2. To estimates specificity (how many false positives are in there), you can evaluate how many of your predictions are supported by the protein hints. This script can print such information: https://github.com/Gaius-Augustus/BRAKER/blob/report/scripts/predictionAnalysis/generateReport.py

> Am I understanding correctly that in the Augustus runs you are using the species parameter file Braker has been training along with prothint.gff and genemark_hintsfile.gff as the --hintsfile input?

Pretty much. Please take a look at the [BRAKER2 paper](https://academic.oup.com/nargab/article/3/1/lqaa108/6066535), it is all explained in detail there.

**Comment by Lamm-a** [comment] 2021-03-22 08:48
Thank for the links and info :) When looking at the `braker.gft` what is the difference between the `gene `and  `transcript`.  I believe understand the hierarchy in `gtf `files is gene -> transcript so is a transcript the just the gene minus `UTRs`?

**Comment by KatharinaHoff** [comment] 2021-03-22 09:26
A gene can have many transcripts.

**Comment by Lamm-a** [comment] 2021-03-22 09:30
@KatharinaHoff But this was an RNA-seq free run so no knowledge of transcripts was provided?

**Comment by KatharinaHoff** [comment] 2021-03-22 09:32
That doesn’t matter for format definition.

GeneMark and AUGUSTUS can predict different isoforms for one gene. Protein
evidence can indicate different isoforms as well.

**Comment by Lamm-a** [comment] 2021-03-22 09:35
Oh okay makes sense, thanks! So comparing the number of transcripts to gene features would tell you very little beyond `number of gene - number of transcripts = number of isoforms`?

**Comment by KatharinaHoff** [comment] 2021-03-22 09:37
Yes.

**Comment by Lamm-a** [comment] 2021-03-22 13:06
> To estimates specificity (how many false positives are in there), you can evaluate how many of your predictions are supported by the protein hints. This script can print such information: https://github.com/Gaius-Augustus/BRAKER/blob/report/scripts/predictionAnalysis/generateReport.py

How do we implement this script? From looking at it it is not a stand alone so i assume is used along with a `Braker `run but can't see where to call it.

**Comment by tomasbruna** [comment] 2021-03-22 18:21
It's not being called during a BRAKER run, yet. For now, it lives in a separate branch because the implementation is not complete. 

Please download all the scripts from https://github.com/Gaius-Augustus/BRAKER/tree/report/scripts/predictionAnalysis to the same folder. Then, call the report-generating script like this:
```
./generateReport.py augustus.hints.gtf hintsfile.gff report.pdf
```

You can also use the `selectSupportedSubsets.py` script to print the more reliable, supported subsets.

Regarding the second question, you can use https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/getAnnoFastaFromJoingenes.py to translate braker.gtf to proteins:

```
getAnnoFastaFromJoingenes.py -g genome.fasta -o BRAKER -f braker.gtf
```

**Comment by Lamm-a** [comment] 2021-03-23 14:08
@tomasbruna Thank you for this. Would it be good practice for the `genome.fasta` to be the soft-masked one or not?

**Comment by KatharinaHoff** [comment] 2021-03-23 14:17
Yes, please softmask your genomes.

**Comment by Lamm-a** [comment] 2021-03-23 14:19
@KatharinaHoff I am meaning for the input of `getAnnoFastaFromJoingenes.py` I have of course used softmasked genomes for the annotation itself

**Comment by KatharinaHoff** [comment] 2021-03-23 14:31
Ah, for this it makes no difference ;-)

**Comment by Lamm-a** [comment] 2021-03-29 10:55
> Please download all the scripts from https://github.com/Gaius-Augustus/BRAKER/tree/report/scripts/predictionAnalysis to the same folder. Then, call the report-generating script like this:
> 
> `./generateReport.py augustus.hints.gtf hintsfile.gff report.pdf`

I have used this tool now but notice that the gene count is different to simply counting the number of "gene" features shown in the braker.gtf output, why would this be so?

**Comment by tomasbruna** [comment] 2021-03-30 22:05
> I have used this tool now but notice that the gene count is different to simply counting the number of "gene" features shown in the braker.gtf output, why would this be so?

Sorry, this is a bug. The tool does not work 100% correct with the format `braker.gtf` is in. That's why it's not yet merged into the master branch, I'll look into fixing that.

> Secondly, is there anywhere i can see the Augustus options used during the runs?

Yes, you will need to run BRAKER with the `--nocleanup` option. Then, in your working directory, you will see a folder named `augustus_files_hints`. There will be a bunch of files called `aug_hints_N`, each has the AUGUSTUS command line inside.

Best,
Tomas

**Comment by Lamm-a** [comment] 2021-04-07 08:42
Hi there,

Was there any progress on fixing the `generateReport.py` script?

Best,
Lamma

**Comment by tomasbruna** [comment] 2021-04-07 15:00
Hi Rob,

unfortunately, no. But I'll look into it soon since there is interest :)

> Thank you :) What format is it optimised for?

I am not really sure why the script does not work with the `braker.gtf`, that will be a part of my investigation...

Best,
Tomas

**Comment by tomasbruna** [comment] 2021-04-07 19:11
Hi Rob,

I pushed a fix to the report branch (https://github.com/Gaius-Augustus/BRAKER/commit/d0f1881fa4f613c7e1d647a0c48e77736920b5c9).

This fixes the report-generating script, but there are still issues with the `braker.gtf` format itself: There can be overlapping transcripts with different gene ids. This makes it look like there are more genes (which are actually just transcript isoforms of the same gene).

If you work directly with transcripts, this is not an issue. Otherwise, you need to collapse the overlapping transcripts into the same gene. Fixing this is already a part of another project, so I do not plan to add it to BRAKER now.

Tomas

**Comment by Lamm-a** [comment] 2021-04-07 19:54
Hi Tomas,

Thank you :) Would that mean the script is semi unusable on `braker.gft` without collapsing the overlapping transcripts? I will have to go learn how to do that!

**Comment by tomasbruna** [comment] 2021-04-07 21:25
Hi Rob,

mostly fully supported transcripts from GeneMark are added to `braker.gtf` (on top of the AUGUSTUS prediction). So `braker.gtf` will have better properties in this kind of evaluation.

> When you yourself use Braker, do you use the braker.gft output? I can't see any reason not to use over the Augustus output?

This really depends on what the task is. GeneMark performs very well on fungal genomes -- so to get a comprehensive set of genes, I would probably take a full union of GeneMark and AUGUSTUS and process them as equals in downstream analysis.

For non-fungal genomes, I'd use `braker.gtf` because AUGUSTUS tends to perform better than GeneMark on non-fungal eukaryotes (but it still needs GeneMark for training). That's the idea behind `braker.gtf` -- only add the most confident GeneMark prediction to the AUGUSTUS result.

**Comment by Lamm-a** [comment] 2021-04-08 07:39
> This really depends on what the task is. GeneMark performs very well on fungal genomes -- so to get a comprehensive set of genes, I would take a full union of GeneMark and AUGUSTUS and process them as equals in downstream analysis.

By this do you mean combine the two outputs irrespective of the support for the GeneMark predictions? For example just simply:

`cat genemark_hintsfile.gff augustus.hints.gtf`

Best
Rob

**Comment by tomasbruna** [comment] 2021-04-09 14:53
> By this do you mean combine the two outputs irrespective of the support for the GeneMark predictions? For example just simply:
> `cat GeneMark-EP/genemark.gtf augustus.hints.gtf > myNew.gtf`

Yes, exactly.

> Secondly do you know if the AGAT's agat_convert_sp_gxf2gxf.pl will play well with your gtf output?

I never tried so I'm not sure.

> It seems to remove a lot of isoform transcripts.

This is probably expected, transcripts in `myNew.gtf` may contain a lot of duplicates -- identical transcripts predicted by both GeneMark and AUGUSTUS.

If you share one of your `myNew.gtf` files and a corresponding converted file, I can take a look at it, to see if everything looks OK.

Best,
Tomas

**Comment by Lamm-a** [comment] 2021-04-09 21:07
Here are the requested files:

The initial combined `gtf`
[PseudaA_sorted_masked.gtf.zip](https://github.com/Gaius-Augustus/BRAKER/files/6288484/PseudaA_sorted_masked.gtf.zip)

The converted gff

**Comment by Lamm-a** [comment] 2021-04-09 21:09
I didn't mean to close the issue whoops! I will get these files to you asap. The conversion timed out on our cluster so will have to restart it.

**Comment by Lamm-a** [comment] 2021-04-13 06:33
Here is the `myNew.gtf`:
[PseudaA_sorted_masked.gtf.zip](https://github.com/Gaius-Augustus/BRAKER/files/6301660/PseudaA_sorted_masked.gtf)

And the corresponding converted `gff`:
[PseudaA_sorted_masked.gff.zip](https://github.com/Gaius-Augustus/BRAKER/files/6301661/PseudaA_sorted_masked.gff)

Do you predict the report `generateReport.py` script to function better on the `myNew.gtf` over `braker.gtf`?
Secondly, given the conversion to `.gff` removes the transcripts, would this alleviate your prior mentioned issues with the report generating script:

> There can be overlapping transcripts with different gene ids. This makes it look like there are more genes (which are actually just transcript isoforms of the same gene).

Best,
Rob

**Comment by Lamm-a** [comment] 2021-04-14 14:43
Whilst converting the `myNew.gtf` to EMBL i had some issues so posted on Biostars and someone from the Swedish Bioinformatics Institute commented the following:



> BTW something is wierd in your GTF file:
> 
> ```
> ANC-D_8901  AUGUSTUS    gene    1   783 0.7 +   .   g4417
> ANC-D_8901  AUGUSTUS    transcript  1   783 0.7 +   .   g4417.t1
> ANC-D_8901  AUGUSTUS    exon    670 783 .   +   .   transcript_id "file_1_file_1_g4417.t1"; gene_id "file_1_file_1_g4417";
> ANC-D_8901  AUGUSTUS    stop_codon  781 783 .   +   0   transcript_id "file_1_file_1_g4417.t1"; gene_id "file_1_file_1_g4417";
> ```
> 
> transcript_id "file_1_file_1_g4417.t1"; gene_id "file_1_file_1_g4417"; must be transcript_id "g4417.t1"; gene_id "g4417"; AGAT will not group the features together because they do not have proper relationships. In top of that I don't get where is the CDS, as you have a stop_codon feature defined.
> 
> If you didn't modify the file, and this is the original BRAKER output you should get in touch with them to show that. There are issues

**Comment by tomasbruna** [comment] 2021-04-24 16:30
I'm closing since the problems were resolved (or are being resolved) in other issues.

**Closed by tomasbruna** 2021-04-24 16:30 UTC
