### ISSUE TITLE
Something wrong about the braker.pl (0 queries aligned.)

### ISSUE THREAD

**Issue by Huangyizhong** [Gaius-Augustus/BRAKER#342] opened 2021-03-18 02:40 UTC
Hi there,
    The BRAKER is a good softwares to do the annotation the genome. I just want to use the  RNA-seq, PACBIO-seq and the proteins from six homology proteins to do the analysis. When I run the  braker.pl like this:
${braker}/braker.pl  --genome=${genome}/bmx01HIFI_v130.fasta.masked \
                     --prot_seq=${protein}/six_protein2.fasta \
                     --hints=${RNA}/sample.hints.gff
                     --etpmode \
                     --softmasking \
                     --cores=40 \
                     --workingdir=$wd
This is a error in the nohup.out file.
..........................................
Reported 0 pairwise alignments, 0 HSPs.
0 queries aligned.
[Thu Mar 18 00:48:39 2021] DIAMOND finished
[Thu Mar 18 00:48:39 2021] Preparing pairs for alignments
[Thu Mar 18 00:49:26 2021] Preparation of pairs finished
[Thu Mar 18 00:49:26 2021] Starting spliced alignment with spaln
[Thu Mar 18 00:49:27 2021] Loading alignment pairs into memory
[Thu Mar 18 00:49:27 2021] Pairs loaded. Number of pairs to align: 0
[Thu Mar 18 00:49:27 2021] Starting the alignments
[Thu Mar 18 00:49:27 2021] 0/0 (100%) pairs aligned
[Thu Mar 18 00:49:27 2021] Alignment of pairs finished
[Thu Mar 18 00:49:27 2021] Translating coordinates from local pair level to contig level
[Thu Mar 18 00:49:28 2021] Finished spliced alignment
[Thu Mar 18 00:49:28 2021] Processing the output
[Thu Mar 18 00:49:28 2021] Output processed
[Thu Mar 18 00:49:28 2021] ProtHint finished.
cat: /home/goldenpigs217/BRAKER/bmx_v130_2/bmx_braker/genemark_hintsfile.gff.prot.tmp: 没有那个文件或目录
ERROR in file /home/goldenpigs217/BRAKER/scripts/braker.pl at line 6302
Failed to execute: cat /home/goldenpigs217/BRAKER/bmx_v130_2/bmx_braker/genemark_hintsfile.gff.rnaseq.tmp /home/goldenpigs217/BRAKER/bmx_v130_2/bmx_braker/genemark_hintsfile.gff.prot.tmp > /home/goldenpigs217/BRAKER/bmx_v130_2/bmx_braker/genemark_hintsfile.gff

Why there were 0 queries aligned (genemark_hintsfile.gff.prot is empty)? Confused about it .

Need your help!
Sincerely 
YIzhong Huang

**Comment by tomasbruna** [comment] 2021-03-18 21:59
Closing since the problem is addressed in https://github.com/gatech-genemark/ProtHint/issues/26

**Closed by tomasbruna** 2021-03-18 21:59 UTC
