### ISSUE TITLE
GeneMark dependency and FAIR workflows

### ISSUE THREAD

**Issue by abretaud** [Gaius-Augustus/BRAKER#629] opened 2023-05-22 13:38 UTC
Hi!
With ERGA/BGE/VGP/EuroScienceGatway/... projects, there are several projects trying to deliver high quality and FAIR workflows for the annotation of genomes. Braker is a very good tool that deserves to be used in this kind of workflows, but I think we are facing a difficult issue with it depending on the non-free GeneMark tool.

Relying on it means that:
- GeneMark can't be redistributed using Conda packages or preconfigured containers
- It makes it impossible to distribute ready-to-use and reproducible workflows
- It makes also automated testing of workflows quite complicated/impossible
- Workflow users are supposed to use their own license file, and provide it somehow to the workflow system, which can be tricky
- In the case of Galaxy, administrators have to decide wether they agree to pre-install GeneMark on computing machines, with all the "legal discomfort" that comes with it

I've experienced these problems with Galaxy, but it will surely be the same for any workflow system like Nextflow of SnakeMake.

Has this issue ever been discussed here? Or maybe with the GeneMark authors? Do you see any way to tackle this problem anytime soon or at longer term?

(ping @bgruening who might be interested too)

**Comment by KatharinaHoff** [comment] 2023-05-22 14:34
As BRAKER developer, I support open source code projects. But you are correct, GeneMark is not fully open source, and not fully free to use. 

Please inquire via e-mail with Mark Borodovsky and Alexandre Lomsadze under which terms GeneMark could be installed in a Galaxy instance. I recently brought that topic to their attention and they replied that it would depend on the specifics of that Galaxy instance.

For the time being, you can install GALBA in your workflows. But that comes with fewer features and lower accuracy in some genomes :-(

**Comment by KatharinaHoff** [comment] 2023-05-22 14:36
Currently, we are allowed to distribute the container with a license key included, i.e. if you pull our docker container, you have the license key inside. However, the license will still expire :-( So a new container will eventually need to be pulled.

**Comment by KatharinaHoff** [comment] 2023-05-23 06:21
> > we are allowed
> 
> Has this been formalized/written somewhere or is it tacit? (I'm not sure of your relationship with the GeneMark authors) Anyway, in the case of Galaxy, "we" can be hard to define: it can be the Galaxy tool author, the Galaxy administrator who will install it, and/or the final user that will run it on its data (for commercial use or not, no quick way to know)

The BRAKER team consists of the group of Mark Borodovsky at Georgia Tech, Tomas Bruna at the JGI, and the group of Mario Stanke at University of Greifswald. We are generally collaborating closely on the development of BRAKER, but most actual code implementation on BRAKER has been done by Tomas Bruna, Lars Gabriel, (Simone Lange a very long time ago), and myself.

Alexandre Lomsadze and Mark Borodvsky have provided us with a GeneMark-ETP version that has the key file included, already. We put that version into our Docker container. I would say that has an official blessing by the GeneMark developers ;-)

> > if you pull our docker container
> 
> We tend to prefer relying on conda packages, because it gives us the ability to switch easily between conda/docker/singularity after writing a single recipe. Maybe having an exception for conda package would be possible thinking ... 

We decided to go with Docker/Singularity instead of Conda because of the C++ components of Augustus. We used to experience linking problems with Conda installations of Augustus, particularly for bam2hints. But you are likely more experienced in shipping this correctly in Conda than we are. Augustus isn't the legal problem, here, anyway.

> > However, the license will still expire
> 
> That's a problem for reproducibility too, and I don't think releasing a time-limited conda package would be good (had some headaches with tbl2asn packages expiring regularly)

I completely agree on that.

This issue needs to be discussed with Mark Borodovsky and Alexandre Lomsadze. I think it is important, because looking at ~1.5 Mio genomes within this decade, we need to scale up.

**Comment by bgruening** [comment] 2023-08-05 08:36
@KatharinaHoff do you think its makes sense to have a joined meeting with you and them? We need to decide soon if we can and want to use GeneMark in ERGA, BGE, VGP and so on ...

**Comment by KatharinaHoff** [comment] 2023-08-28 10:14
I am willing to participate in a call, I support your mission. Please also include @MarioStanke if you plan such a meeting.

**Comment by KatharinaHoff** [comment] 2023-11-20 16:31
GeneMark-ETP is now under a different license. The key dependency was dropped. I am closing here because the issue is probably solved, now.

**Closed by KatharinaHoff** 2023-11-20 16:31 UTC
Labels: ETP
