### ISSUE TITLE
Failed to execute: mv .rnaseq.tmp

### ISSUE THREAD

**Issue by reubwn** [Gaius-Augustus/BRAKER#35] opened 2019-04-24 11:07 UTC
Hello,

I'm running BRAKER using only proteins from a closely related species, as per your recipe in Fig 5 of the (excellent, by the way) help page. Full command is below:
```
~/software/BRAKER/scripts/braker.pl \
--genome=genome.fa \
--species=my_species --useexisting \
--prot_seq=proteins.faa --prg=gth --gth2traingenes --trainFromGth --gff3 --cores=1 \
--AUGUSTUS_CONFIG_PATH=/path/to/config/ \
--AUGUSTUS_BIN_PATH=/path/to/bin/ \
--AUGUSTUS_SCRIPTS_PATH=/path/to/scripts/ \
--BAMTOOLS_PATH=/path/to/bamtools/bin/ \
--GENEMARK_PATH=/path/to/genemark/bin/ \
--SAMTOOLS_PATH=/path/to/samtools \
--ALIGNMENT_TOOL_PATH=/path/to/gth
```

It fails with these messages to STDOUT:
```
# Wed Apr 24 11:10:56 2019: Log information is stored in file /path/to/braker.log
Use of uninitialized value $genemark_hintsfile in concatenation (.) or string at ~/software/BRAKER/scripts/braker.pl line 5005.
Use of uninitialized value $genemark_hintsfile in concatenation (.) or string at ~/software/BRAKER/scripts/braker.pl line 5006.
Use of uninitialized value $genemark_hintsfile in concatenation (.) or string at ~/software/BRAKER/scripts/braker.pl line 5075.
mv: missing destination file operand after ‘.rnaseq.tmp’
Try 'mv --help' for more information.
ERROR in file ~/software/BRAKER/scripts/braker.pl at line 5079
Failed to execute: mv .rnaseq.tmp 
```

and the last entry in `braker.log` is:
```
# Wed Apr 24 11:37:14 2019: Filtering intron hints for GeneMark from /path/to/my_species/hintsfile.gff...
cat .prot | sort -n -k 4,4 | sort -s -n -k 5,5 | sort -s -k 3,3 | sort -s -k 1,1 | /path/to/join_mult_hints.pl > .prot.tmp
mv .rnaseq.tmp 
```

I'm guessing it thinks there should be some RNA-seq evidence, as per `$genemark_hintsfile`, and fails when `mv` throws an error when it does not find it? Is this a bug, or perhaps I am missing a flag in my command?

Many thanks,
reubwn

PS: I updated the repo immediately before running this command.

**Comment by max-biodatomics** [comment] 2019-05-01 18:09
I have the same issue

**Comment by max-biodatomics** [comment] 2019-05-01 22:57
Looks like the code is the mess now. 
I used: braker.pl --species=AJ1 --genome=clasified-AJ1-scaffolds.fasta --prot_seq=Proteins-Cl.aa.fasta --prg=gth --trainFromGth --cores=30 --fungus

There many errors with internal variables $EPmode and $ETPmode. 
In my case, it should be $EPmode = 1 and $ETPmode = 0.
Yet, when this line executed both are 0. 

I tried to modify $EPmode at file beginning I got a new error. 
if I change $EPmode around line 5074 then I pass well these conditions. I have checked that I have only a correct set of files. 

But I got a new error. 
# Wed May  1 22:08:37 2019: Log information is stored in file /home/ubuntu/nvme1/kraken-filtered/braker/AJ1/braker.log
ERROR in file /opt/BRAKER/scripts/braker.pl at line 6140
Failed to execute: /opt/augustus-3.3.2/bin/etraining --species=AJ1 --AUGUSTUS_CONFIG_PATH=/home/ubuntu/augustus_config/ /home/ubuntu/nvme1/kraken-filtered/braker/AJ1/train.f.gb 1> /home/ubuntu/nvme1/kraken-filtered/braker/AJ1/gbFilterEtraining.stdout 2>/home/ubuntu/nvme1/kraken-filtered/braker/AJ1/errors/gbFilterEtraining.stderr

by repeating the last command I found:
Could not find the config file /home/ubuntu/augustus_config/species/AJ1/AJ1_parameters.cfg.
 Looking for AJ1_parameters.cfg in the configuration directory instead ... not found.

so, the current version is completely messed.

**Comment by djwcisel** [comment] 2019-05-24 02:41
I'm getting same problem with my data. Test4 also fails with the same output.

When I run my data with just a .bam file but no protein file, it works fine. However, just running protein or running protein and .bam fails.

**Comment by KatharinaHoff** [comment] 2019-08-16 14:11
Hi!

There was a bit of a mess with the different prediction modes, correct. However, I think the problems are fixed, now (probably fixed with commit https://github.com/Gaius-Augustus/BRAKER/commit/e117150b8ad66ecf7cd5828c7f7fe476a4a8c191).

I just confirmed that test4.sh (training from GenomeThreader genes, no RNA-Seq) works ok with the current github code; test5.sh (training from RNA-Seq with GeneMark-ET and using GenomeThreader alignments as evidence for prediction only) also passed ok. 

Katharina

**Closed by KatharinaHoff** 2019-08-16 14:11 UTC
