### ISSUE TITLE
Repeated exons in predicted transcripts

### ISSUE THREAD

**Issue by jmpolinski** [Gaius-Augustus/BRAKER#653] opened 2023-07-25 21:04 UTC
In my output GTF, I am finding repeated exons in separate gene models, always predicted by the two different ab initio programs (augustus and geneMark). This is the second genome for which I've seen this issue. The BRAKER version was v2.1.6 (run in Oct. 2021 and Jan. 2023, prior to Braker3 release).  

I did not see others reporting this issue so is it a configuration/installation issue on my end?  
Or is this a known issue that has been resolved in Braker3?  

Example:  
scaffold_45	AUGUSTUS	CDS	10593039	10593080	1	+	0	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	10593859	10593896	1	+	0	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	10594608	10594786	1	+	1	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	10595390	*10595583*	1	+	2	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	*10596138	10596266*	1	+	0	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	*10596435	10596541*	1	+	0	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	*10597460*	10597567	1	+	1	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	AUGUSTUS	CDS	10597631	10597745	0.99	+	1	transcript_id "Cbor-rna_g15328.t1"; gene_id "Cbor-rna_g15328";
scaffold_45	GeneMark.hmm3	CDS	10595422	*10595583*	.	+	0	transcript_id "Cbor-rna_g15329.t1"; gene_id "Cbor-rna_g15329";
scaffold_45	GeneMark.hmm3	CDS	*10596138	10596266*	.	+	0	transcript_id "Cbor-rna_g15329.t1"; gene_id "Cbor-rna_g15329";
scaffold_45	GeneMark.hmm3	CDS	*10596435	10596541*	.	+	0	transcript_id "Cbor-rna_g15329.t1"; gene_id "Cbor-rna_g15329";
scaffold_45	GeneMark.hmm3	CDS	*10597460*	10597601	.	+	1	transcript_id "Cbor-rna_g15329.t1"; gene_id "Cbor-rna_g15329";

**Comment by LarsGab** [comment] 2023-07-26 07:19
Hi,

This is not a bug, but rather a feature of BRAKER/AUGUSTUS. These two transcripts represent distinct isoforms of the same gene, resulting from alternative splicing. It is possible that some of their CDS may be identical.

Best,
Lars

**Comment by jmpolinski** [comment] 2023-07-26 12:41
These are not isoforms, and BRAKER2 is treating them differently than isoforms. As you can see in the example, they have distinct gene IDs, whereas proper isoforms (which exist in this gene set) have the same gene ID and transcript IDs that contain that gene ID plus ".t#" to indicate the isoform.   

In several cases, though not the example above, one Augustus gene has identical exons to two separate GeneMark predictions - indicating that either Augustus incorrectly merged two genes or GeneMark split one. In either case, all 3 genes should not be in the output. 

The overlapping exons for predictions with different gene IDs is causing issues in downstream analyses because filtering for the longest isoform does not remove one.

**Comment by KatharinaHoff** [comment] 2023-11-20 16:23
I am closing here, Lars provided an answer.

**Closed by KatharinaHoff** 2023-11-20 16:23 UTC
Labels: question
