### ISSUE TITLE
error executing gmes_petap.pl

### ISSUE THREAD

**Issue by WenhaoLiu0218** [Gaius-Augustus/BRAKER#203] opened 2020-04-27 07:53 UTC
Hi,

I got an error when running BRAKER2, it looks like something wrong with GeneMark. The error message at GeneMark-ES.stderr is :

running gm.hmm on local multi-core system
12796 contigs in training
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_836.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_836
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_6689.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_6689
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_11575.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_11575
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_645.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_645
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_2763.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_2763
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_1382.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Algae/E/03.gene_anno/braker/braker/GeneMark-ES/output/data/dna.fa_1382
12796 contigs in training
error, file not found /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmes_petap.pl: output/gmhmm/dna.fa_6689.out

I can not deal with this problem and it would be very grateful if i can get some responses!

**Comment by WenhaoLiu0218** [comment] 2020-05-08 06:04
Thanks for your reply! 

We ran the test for BRAKER2 and it works successful. Actually, we meet the same problem with different genomes, although for other genomes BRAKER works well. We also checked the input data, it looks normal, so we guess maybe something wrong with GeneMark? Here i will take an example:

the tail of error message at GeneMark-ES.stderr is : 
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_8862.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/data/dna.fa_8862
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_191616.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/data/dna.fa_191616
warning on: /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_139533.out  /hwfssz1/ST_AGRIC/F13ZHQYJSY1409_LP/USER/wanghongli/Moss_Liverworts/D/03.gene_anno/braker/GeneMark-ES/output/data/dna.fa_139533
208805 contigs in training
**error, file not found /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmes_petap.pl: output/gmhmm/dna.fa_125799.out**

then we reran gmhmme3 alone with the sequence dna.fa_125799 in a new directory (/hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3  -m gmhmm.mod -f lst -n  -o  dna.fa_125799.out dna.fa_125799), it reported "**segmentation fault**" without any output file.

the dna.fa_125799 is:
>dna.fa_125799	211637_dna	1	1337
GACAGCCTGGGTTGATCGGTCTGGGTGAACGCGGGTTCGGGCCTTGCTGCCGTACCCCCCAATTGCGAGACCAAATCGTGATTGACCACACACAATTCGG
ACATTAACTTCGGCTACCGCTTCAATTTGGCGGGTGCCGGAAGCGGGCGCCTTCGTCGTTTGCCATCCAAAACCTCAACCTCTGGAACAACATGAACACC
CAAGCTCCCGCGTTTTCCACCATGTCCAAGCTCGCCCTGCGCATGGGGCTTTGTGCCGCTGCGCTGGTCGGCGCCATGTCCAGCGCCAGCGCGGCCATCG
TCACGTTCACCACGCCGATTGCTGTGACGAACTCGTTCGACGGCATCTATGTCAATTTCCTGACCGGTGCATCGGGCGCGACCGGCGGCGCAACGCCAGG
CTGGGACTTCAACCCCTACAACTCGGGCACGACGCTGAGCTTTTTCTGGAGTGCCACACCCAGCCAGGCCAGCGGCGTTGCTTCCACGACGACCGGCCCG
TACCTTGATCTGGCGCCTGGCACAACCATCTCGGCTGCATCGACGTTCGCCCAAGTCACTGCAACGGCCGCCACGGCCCCGTTCCAGGTCGTCGGTACCC
ACACCCTGGGCTTCAGGTTTTATAACGAGACAACCGCCACCATCAACTATGGCTACGCCACATTGAGCACCGGTGCGACGGGCGGATTCCCGCTGACCAT
CACGCGCTGGAGTTTCGAGAACACGGGCGCTGCCATCTCCACCCCGGTGCCTGAGCCCGCCACGGGCGCCATGCTGGCCGTGGGCGCATTGGCGCTTGGC
GCGCTGAAGCTGCGCCGCAACCGCCGCCAGCAACCCGCGTAAGCAAGCCGGCTGAGCAGCAAGTACGGCGGGCAAGCACCGCCAGCAAGCACGGCCAGTT
GGTACTGTTTCAAAGGATTCAAAGCGCAACGCGCCTGCGCCGATTTCAGCGCAGGCGCGTTGTCATTTGCGGCGGTCAGTTGCCTGGCTGCAGCAGCGCG
CGCAAGGGGTCAAGCAGGGGGCCGTAGCCAGCGGCCGGTGTCGATGTTTTTTTCATCGGCTGGCGCACCTGCAACGCGCTGGGCGTGCGGATGGCGCGCT
GGGCGTTCTGGAACTGCAGGCATTGCGGCTCGAACGGCAGGCCGCAGAAATCCAGCAGTTCGCGGATCTGTTCCTCGGGCCTGGCCACCAGCGCTTCGTA
TTGCTGCACCCGAAACCGTTGCGGATAGCGTGCAGCCCAAAAACGGCACAGGCTGTCGTAGGCCTGCCAGTAGGCGCCCAGGCCTTCAAAGCTGTAGGTG
AAGTTCACACGGTCGGGGCCGAACAGCTGCTTGTAGC

**Comment by tomasbruna** [comment] 2020-05-12 00:30
Hello,

can you send me (bruna.tomas@gmail.com) the `gmhmm.mod` file which is used as input in the command that fails?

    /hwfssz1/ST_AGRIC/USER/xuyan/software/gmes_linux_64/gmhmme3 -m gmhmm.mod -f lst -n -o dna.fa_125799.out dna.fa_125799

I will try to reproduce this error.

Thanks!
Tomas

**Comment by WenhaoLiu0218** [comment] 2020-05-12 08:27
Hi,

here is attached gmhmm.mod file.
[gmhmm.mod.zip](https://github.com/Gaius-Augustus/BRAKER/files/4614240/gmhmm.mod.zip)

**Comment by tomasbruna** [comment] 2020-05-20 02:06
Hello @WenhaoLiu0218,

sorry for the late reply, can you re-upload the gmhmm.mod.zip file? Maybe it expired, I cannot download it right now.

In the meantime, I tried running `gmhmme3` with a generic `.mod` file on the problematic contig and everything worked fine. Let's hope we can reproduce the error with your `.mod`. file.

Tomas

**Comment by WenhaoLiu0218** [comment] 2020-05-20 02:35
Hello, Tomáš,
Thank you for replying to me.
We found that all the genomes which producing BRAKER error have lots of
short sequences, and most of them have more than 7000 sequences, in order
to test whether it is caused by this reason, we only selected sequences
which are longer than 5000bp (#1900+), finally, the software worked fine!
So is the GeneMark cannot deal with genome with too many short sequences?
Also, I attached the gmhmm.mod file.

Best regards.

Tomáš Brůna <notifications@github.com> 于2020年5月20日周三 上午10:06写道：

**Comment by tomasbruna** [comment] 2020-05-20 02:49
Happy to hear you managed to solve the problem! I cannot think of any reason why too many short sequences should be a problem in GeneMark, maybe the `.mod` file will help. Can you send an email with the `.mod` file to bruna.tomas@gmail.com? Something went wrong with the attachment again, I cannot see it.

**Comment by xvtyzn** [comment] 2020-07-01 08:40
Hi, 

I have the same issue. 
Our genome has 378,040 sequences and many of them are short in sequence length. Could this be the cause of the problem?

```
378042 contigs in training
warning on: /home/ide/bin/gm_et_linux_64/gmhmme3  -m /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_370551.out  /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/data/dna.fa_370551
warning on: /home/ide/bin/gm_et_linux_64/gmhmme3  -m /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_377973.out  /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/data/dna.fa_377973
warning on: /home/ide/bin/gm_et_linux_64/gmhmme3  -m /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/gmhmm.mod   -f lst -n   -o output/gmhmm/dna.fa_355557.out  /home/ide/korogi/Gene_prediction/2020/gryllus_bimaculatus/Braker2/20200623_cpu1/GeneMark-ET/output/data/dna.fa_355557
378042 contigs in training
error, file not found /home/ide/bin/gm_et_linux_64/gmes_petap.pl: output/gmhmm/dna.fa_370551.out
```

Has the problem here already been resolved? 
If you have solved it, I would appreciate it if you could tell me how to fix it.

Thanks

Keigo

**Comment by KatharinaHoff** [comment] 2020-07-01 09:39
Just a general comment: I always remove short contigs prior annotation.
Yes, I recommend that. E.g. for training I discard everything shorter 5000
nt, for prediction (if we annotate short contigs at all) we might
re-include them.

Katharina

**Comment by xvtyzn** [comment] 2020-07-01 09:58
Thanks for your reply! I will follow your suggestion and try to run it again.

Best regards,

Keigo

**Comment by tomasbruna** [comment] 2020-08-24 19:02
After a long time, this error was finally fixed in GeneMark. Please download the latest version (4.61 or higher) from http://topaz.gatech.edu/GeneMark/license_download.cgi to get the fix.

**Closed by tomasbruna** 2020-08-24 19:02 UTC
