### ISSUE TITLE
 the output file of augustus.hints.gff3 condn't be used for EVidenceModeler

### ISSUE THREAD

**Issue by wuxiaopei0509** [Gaius-Augustus/BRAKER#123] opened 2019-11-22 11:44 UTC
Hi,
I want to use the augustus.hints.gff3 produced by braker2 as ab intio gene predictions to EVidenceModeler (aka EVM) software  and to combine ab intio gene predictions, protein and transcript alignments into weighted consensus gene structures .However the augustus.hints.gff3  can not be used.I also use augustus_GFF3_to_EVM_GFF3.pl to convert the augustus.hints.gff3 file.However the output file also doesn't work. Does any one who have the same issue and how to slove it ?

**Comment by KatharinaHoff** [comment] 2019-11-22 11:49
The augustus_GFF3_to_EVM_GFF3.pl script probably doesn't work because it was designed to convert the native augustus gff3 format (which is kind of incorrect). BRAKER does not output that format, but the output of gtf2gff.pl, which I recently fixed to be compatible with another tools (https://github.com/Gaius-Augustus/Augustus/issues/74). 

Do you have working gff3 model file from another tool (e.g. SNAP converted or similar)? This is going to be some small format difference, and I can look into this if you provide me with an example.

Katharina

**Comment by wuxiaopei0509** [comment] 2019-11-22 12:29
Yes，I also use SNAP_to_GFF3.pl and glimmerHMM_to_GFF3.pl which are included in EVidenceModeler and can successfully convert SNAP and glimmerHMM output to gff3
 file that EVidenceModeler needed. Now is just the  augustus.hints.gff3 produced by braker2 cannot be converted successfully converted . I will try gtf2gff.pl next.

**Comment by KatharinaHoff** [comment] 2019-11-22 12:36
That probably won’t solve your problem because the file that you try to convert was produced by gtf2gff.pl.

If you just posted a few lines of one of the compatible output files (e.g. the converted snap file end product), I can check what’s different from our output.

**Comment by wuxiaopei0509** [comment] 2019-11-22 12:53
ok,the compatible snap file produced by SNAP_to_GFF3.pl is like:
![图片](https://user-images.githubusercontent.com/52643750/69427119-d08f4980-0d69-11ea-8255-e669c9f30a36.png)
The issue for me is the result of augustus.hints.gff3 is best and I need to convert this file which is compatible with EVidenceModeler. Are there some solutions?
Thank you very much!

**Comment by wuxiaopei0509** [comment] 2019-11-22 13:47
Hi,I use gtf2gff.pl you suggested to convert augustus.hints.gtf to gff3.Indeed,I use /EVidenceModeler-1.1.1/EvmUtils/gff3_gene_prediction_file_validator.pl  to check the gff3 file whether it is compatible with EVidenceModeler. Is there any solutions about this issue?

**Comment by KatharinaHoff** [comment] 2019-11-22 14:03
I added a new script add_name_to_gff3.pl to the Augustus repository for your purpose. It will convert a gff3 output of gtf2gff.pl to something that hopefully is compatible with EVM. Please let me know whether it works.
https://github.com/Gaius-Augustus/Augustus/commit/6e664932a5839f210560b42835f9485cbc5b2664

**Comment by wuxiaopei0509** [comment] 2019-11-22 14:20
Thank you very much! by the way ,could you tell me how to use this script? I test it but occurs error.
Best

**Comment by wuxiaopei0509** [comment] 2019-11-22 14:35
I test the script with ./add_name_to_gff3.pl <augustus.gff3 --out=out.gff3 and it occurs:
![图片](https://user-images.githubusercontent.com/52643750/69434332-5a461380-0d78-11ea-9247-6a046efa70b2.png)

**Comment by KatharinaHoff** [comment] 2019-11-22 14:40
I am surprised to see this. Usage should be:

`add_name_to_gff3.pl < test.gff3 --out=out.gff3 --filter`
 
I am sitting on a train. Maybe code did not get transferred to the server completely. I am trying to push again. Nope, cannot push again. Hhm, weird. Because I did test it (with the example in usage in the script).

**Comment by KatharinaHoff** [comment] 2019-11-22 14:46
Did you git clone/git pull Augustus? If you saved the code display of the website, that would explain the weird message....

**Comment by wuxiaopei0509** [comment] 2019-11-23 08:29
It is very kind of you.I try it again and the script works.
Best!

**Comment by U201412486** [comment] 2019-12-07 05:57
Hi,
  I just use the output file of augustus.hints.gff3 produced by braker to run EVM.And it reports error  like below,
  `-scoring exons (strand: -)Error with prediction: AUGUSTUS lend_intergenic: 78582, rend_intergenic: 78571  at /EVidenceModeler-1.1.1/EvmUtils/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 78600, rend_intergenic: 78571  at /EVidenceModeler-1.1.1/EvmUtils/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 78797, rend_intergenic: 78738  at /EVidenceModeler-1.1.1/EvmUtils/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 78797, rend_intergenic: 78738  at /EVidenceModeler-1.1.1/EvmUtils/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 79735, rend_intergenic: 79689  at /EVidenceModeler-1.1.1/EvmUtil
s/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 79735, rend_intergenic: 79689  at /EVidenceModeler-1.1.1/EvmUtil
s/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 80048, rend_intergenic: 79965  at /EVidenceModeler-1.1.1/EvmUtil
s/.././evidence_modeler.pl line 3218.
Error with prediction: AUGUSTUS lend_intergenic: 80048, rend_intergenic: 79965  at /EVidenceModeler-1.1.1/EvmUtil
s/.././evid`
   According to your discussion,does it means that the output file of augustus.hints.gtf produced by braker will fit EVM after I run the code below ?
 `../gtf2gff.pl <augustus.hints.gtf --out=augustus.hints1.gff3 --gff3
../add_name_to_gff3.pl < augustus.hints1.gff3 --out=augustus.hints2.gff3 --filter
/EVidenceModeler-1.1.1/EvmUtils/misc/augustus_GFF3_to_EVM_GFF3.pl augustus.hints2.gff3 >augustus.hints3.gff3`
  Then I use augustus.hints3.gff3 to run EVM,does it will success?

**Comment by U201412486** [comment] 2019-12-07 06:57
Hi,
  I do it ,It still report error as the same as the before.
  Do you have the same error?  @wuxiaopei0509

**Comment by wuxiaopei0509** [comment] 2019-12-10 00:48
I work well

**Comment by U201412486** [comment] 2019-12-10 01:09
Can you tell me how the EVM input files are  produced ? @wuxiaopei0509 
  Thanks,

**Comment by wuxiaopei0509** [comment] 2019-12-17 11:12
I create gene_predictions.gff3、protein_alignments.gff3 and transcript_alignments.gff3 file ,the  gene_predictions.gff3 comes from braker2 and are transformed use gtf2gff.pl /add_name_to_gff3.pl/augustus_GFF3_to_EVM_GFF3.pl to obtain the format EVM recepted. the protein_alignments.gff3 comes from GeMoMa and be transformed by GeMoMa_gff_to_gff3.pl which can be obtained at the EVM softwate set. and last the transcript_alignments.gff3 file comes from pasa assembly

**Comment by U201412486** [comment] 2019-12-17 12:38
Thank you for your reply.

**Closed** 2020-03-07 07:40 UTC
